/*
 * DemoUIRuntime — per-flow-graph factory for the DemoUI UI-FBP module.
 * Generated by CodeNodeIO UIFBPInterfaceGenerator (feature 087 / Design B)
 * License: Apache 2.0
 */

package io.codenode.testmodule.controller

import io.codenode.fbpdsl.model.FlowGraph
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.runtime.DynamicPipelineController
import io.codenode.fbpdsl.runtime.ModuleController
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import io.codenode.testmodule.nodes.DemoUISourceCodeNode
import io.codenode.testmodule.nodes.DemoUISinkCodeNode
import io.codenode.testmodule.iptypes.CalculationResults

/**
 * Constructs a DemoUIControllerInterface backed by [DynamicPipelineController].
 * Per-flow-graph state lives in this function's closure — multiple
 * concurrent calls produce fully isolated controllers.
 */
fun createDemoUIRuntime(flowGraph: FlowGraph): DemoUIControllerInterface {
    val _results = MutableStateFlow<CalculationResults?>(null)
    val _a = MutableSharedFlow<Double>(replay = 1, extraBufferCapacity = 64)
    val _b = MutableSharedFlow<Double>(replay = 1, extraBufferCapacity = 64)
    val _c = MutableSharedFlow<Double>(replay = 1, extraBufferCapacity = 64)

    val sinkWrapper = DemoUISinkCodeNode.withReporters(
        { value -> _results.value = value as CalculationResults? }
    )
    val sourceWrapper = DemoUISourceCodeNode.withSources(_a, _b, _c)

    val controller = DynamicPipelineController(
        flowGraphProvider = { flowGraph },
        lookup = { nodeName -> when (nodeName) {
            "DemoUISource" -> sourceWrapper
            "DemoUISink" -> sinkWrapper
            else -> null
        } },
        onReset = {
            _results.value = null
        }
    )

    return object : DemoUIControllerInterface, ModuleController by controller {
        override val results: StateFlow<CalculationResults?> = _results.asStateFlow()
        override fun emitA(value: Double) {
            controller.coroutineScope?.launch { _a.emit(value) }
        }
        override fun emitB(value: Double) {
            controller.coroutineScope?.launch { _b.emit(value) }
        }
        override fun emitC(value: Double) {
            controller.coroutineScope?.launch { _c.emit(value) }
        }
    }
}
