/*
 * DemoUIRuntime — Universal-runtime factory for the DemoUI UI-FBP module
 * Generated by CodeNodeIO UIFBPInterfaceGenerator
 * License: Apache 2.0
 */

package io.codenode.testmodule.controller

import io.codenode.fbpdsl.model.FlowGraph
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.runtime.DynamicPipelineController
import io.codenode.fbpdsl.runtime.ModuleController
import io.codenode.testmodule.viewmodel.DemoUIState
import io.codenode.testmodule.nodes.DemoUISourceCodeNode
import io.codenode.testmodule.nodes.DemoUISinkCodeNode

/**
 * Module-local lookup for resolving node names to compiled CodeNodeDefinitions.
 * Used by [DynamicPipelineController] when running this module without the GraphEditor.
 */
object DemoUINodeRegistry {
    fun lookup(nodeName: String): CodeNodeDefinition? = when (nodeName) {
        "DemoUISource" -> DemoUISourceCodeNode
        "DemoUISink" -> DemoUISinkCodeNode
        else -> null
    }
}

/**
 * Constructs a DemoUIControllerInterface backed by [DynamicPipelineController].
 * Production-app consumers call this directly. The returned object delegates
 * every [ModuleController] member to the underlying controller and reads typed
 * state flows directly from DemoUIState.
 */
fun createDemoUIRuntime(flowGraph: FlowGraph): DemoUIControllerInterface {
    val controller = DynamicPipelineController(
        flowGraphProvider = { flowGraph },
        lookup = DemoUINodeRegistry::lookup,
        onReset = DemoUIState::reset
    )
    return object : DemoUIControllerInterface, ModuleController by controller {
        override val results = DemoUIState.resultsFlow
    }
}
