/*
 * DemoUIControllerInterface
 * Generated by CodeNodeIO UIFBPInterfaceGenerator (feature 087 / Design B additive)
 * License: Apache 2.0
 */

package io.codenode.testmodule.controller

import io.codenode.fbpdsl.runtime.ModuleController
import kotlinx.coroutines.flow.StateFlow
import io.codenode.testmodule.iptypes.CalculationResults

/**
 * Typed control surface for DemoUI.
 *
 * Inherits start/stop/pause/resume/reset/getStatus/setAttenuationDelay/
 * setEmissionObserver/setValueObserver and executionState from [ModuleController].
 * Adds typed StateFlow members for each sink-input port the UI observes
 * AND additive emit<Port>(value) methods for each source-output port the UI raises
 * (Design B / FR-007 additive).
 */
interface DemoUIControllerInterface : ModuleController {
    val results: StateFlow<CalculationResults?>
    fun emitA(value: Double)
    fun emitB(value: Double)
    fun emitC(value: Double)
}
