/*
 * DemoUIControllerInterface
 * Generated by CodeNodeIO UIFBPInterfaceGenerator
 * License: Apache 2.0
 */

package io.codenode.testmodule.controller

import io.codenode.fbpdsl.runtime.ModuleController
import kotlinx.coroutines.flow.StateFlow
import io.codenode.testmodule.iptypes.CalculationResults

/**
 * Typed control surface for DemoUI.
 *
 * Inherits start/stop/pause/resume/reset/getStatus/setAttenuationDelay/
 * setEmissionObserver/setValueObserver and executionState from [ModuleController].
 * Adds typed StateFlow members for each sink-input port the UI observes.
 */
interface DemoUIControllerInterface : ModuleController {
    val results: StateFlow<CalculationResults?>
}
