/*
 * EALogicPreviewProvider — Registers EALogic preview composables for the runtime panel
 * Generated by CodeNodeIO PreviewProviderGenerator
 * License: Apache 2.0
 */

package io.codenode.expenseapproval.userInterface

import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import io.codenode.expenseapproval.viewmodel.EALogicViewModel
import io.codenode.previewapi.PreviewRegistry

/**
 * Provides preview composables that render EALogic components,
 * driven by the RuntimeSession's ViewModel state.
 *
 * Per feature 087 / Design B, the registered lambda is the host-app
 * "ScreenRoot" seam: it collects `viewModel.state` as Compose state and
 * passes `viewModel::onEvent` to the pure two-parameter EALogicUserInterface Screen.
 */
object EALogicPreviewProvider {

    /**
     * Registers EALogic preview composables with the PreviewRegistry.
     */
    fun register() {
        PreviewRegistry.register("EALogic") { viewModel, modifier ->
            val vm = viewModel as EALogicViewModel
            val state by vm.state.collectAsState()
            EALogicUserInterface(state = state, onEvent = vm::onEvent, modifier = modifier)
        }
    }
}
