/*
 * ExpenseApprovalLogicPreviewProvider — Feature 110 generated single-slot preview registration
 * Generated by CodeNodeIO PreviewProviderGenerator
 * License: Apache 2.0
 */

package io.codenode.expenseapproval.userInterface

import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import io.codenode.expenseapproval.viewmodel.ExpenseApprovalLogicViewModel
import io.codenode.previewapi.PreviewComposable
import io.codenode.previewapi.PreviewSlot

/**
 * Exposes a single `val preview: PreviewComposable` field. The graphEditor's
 * Runtime Preview panel reads this field via reflection on canvas load of the
 * matching `<Prefix>.flow.kt` and dispatches the lambda inside a `@Composable`
 * context. Per feature 087 / Design B, the lambda IS the host-app "ScreenRoot"
 * seam: collects `vm.state` as Compose state and passes `vm::onEvent` to the pure
 * two-parameter ExpenseApprovalLogicUserInterface Screen.
 */
object ExpenseApprovalLogicPreviewProvider {
    val preview: PreviewComposable = { viewModel, modifier ->
        val vm = viewModel as ExpenseApprovalLogicViewModel
        val state by vm.state.collectAsState()
        ExpenseApprovalLogicUserInterface(state = state, onEvent = vm::onEvent, modifier = modifier)
    }

    /**
     * Installs [preview] into the panel-observed [PreviewSlot]. Reflectively
     * invoked by `PreviewProviderResolver` after successful Class.forName + init.
     * Plain function (no Composer needed) so the reflection call is trivial.
     */
    fun install() {
        PreviewSlot.set(preview)
    }
}
