/*
 * UserProfilesViewModel
 * Generated by CodeNodeIO RuntimeViewModelGenerator
 * License: Apache 2.0
 */

package io.codenode.userprofiles

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import io.codenode.fbpdsl.model.ExecutionState
import io.codenode.fbpdsl.model.FlowGraph
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import io.codenode.userprofiles.generated.UserProfilesControllerInterface
import io.codenode.userprofiles.persistence.UserProfileDao
import io.codenode.userprofiles.persistence.UserProfileEntity
import io.codenode.userprofiles.persistence.UserProfileRepository

// ===== MODULE PROPERTIES START =====
// Auto-generated from source output ports and sink input ports. Do not edit this section manually.
// Changes here will be overwritten on next code generation.

object UserProfilesState {

    internal val _save = MutableStateFlow<Any?>(null)
    val saveFlow: StateFlow<Any?> = _save.asStateFlow()

    internal val _update = MutableStateFlow<Any?>(null)
    val updateFlow: StateFlow<Any?> = _update.asStateFlow()

    internal val _remove = MutableStateFlow<Any?>(null)
    val removeFlow: StateFlow<Any?> = _remove.asStateFlow()

    internal val _result = MutableStateFlow<Any?>(null)
    val resultFlow: StateFlow<Any?> = _result.asStateFlow()

    internal val _error = MutableStateFlow<Any?>(null)
    val errorFlow: StateFlow<Any?> = _error.asStateFlow()

    internal val _profiles = MutableStateFlow<List<UserProfileEntity>>(emptyList())

    fun reset() {
        _save.value = null
        _update.value = null
        _remove.value = null
        _result.value = null
        _error.value = null
        _profiles.value = emptyList()
    }
}

// ===== MODULE PROPERTIES END =====





// ============================================================
// ViewModel
// Binding interface between composable UI and FlowGraph.
// User-editable section below — preserved across regenerations.
// ============================================================

/**
 * ViewModel for the UserProfiles composable.
 * Bridges FlowGraph domain logic with Compose UI.
 *
 * @param controller The UserProfilesControllerInterface that manages FlowGraph execution
 * @generated by CodeNodeIO RuntimeViewModelGenerator
 */
class UserProfilesViewModel(
    private val controller: UserProfilesControllerInterface,
    userProfileDao: UserProfileDao
) : ViewModel() {

    // Observable state from module properties
    val result: StateFlow<Any?> = UserProfilesState.resultFlow
    val error: StateFlow<Any?> = UserProfilesState.errorFlow

    // Reactive profile list from repository
    val profiles: StateFlow<List<UserProfileEntity>> = UserProfilesState._profiles

    // Execution state from controller
    val executionState: StateFlow<ExecutionState> = controller.executionState

    init {
        // Collect repository changes into the profiles StateFlow
        viewModelScope.launch {
            val repo = UserProfileRepository(userProfileDao)
            repo.observeAll().collect { list ->
                UserProfilesState._profiles.value = list
            }
        }
    }

    // CRUD methods — trigger operations via the FlowGraph reactive source
    fun addEntity(userProfile: UserProfileEntity) {
        UserProfilesState._save.value = userProfile
    }

    fun updateEntity(userProfile: UserProfileEntity) {
        UserProfilesState._update.value = userProfile
    }

    fun removeEntity(userProfile: UserProfileEntity) {
        UserProfilesState._remove.value = userProfile
    }

    // Control methods
    fun start(): FlowGraph = controller.start()

    fun stop(): FlowGraph = controller.stop()

    fun reset(): FlowGraph = controller.reset()

    fun pause(): FlowGraph = controller.pause()

    fun resume(): FlowGraph = controller.resume()
}

