/*
 * UserProfilesViewModel
 * Generated by CodeNodeIO RuntimeViewModelGenerator
 * License: Apache 2.0
 */

package io.codenode.userprofiles

import androidx.lifecycle.ViewModel
import io.codenode.fbpdsl.model.ExecutionState
import io.codenode.fbpdsl.model.FlowGraph
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import io.codenode.userprofiles.generated.UserProfilesControllerInterface

// ===== MODULE PROPERTIES START =====
// Auto-generated from sink node input ports. Do not edit this section manually.
// Changes here will be overwritten on next code generation.

object UserProfilesState {

    internal val _result = MutableStateFlow(null)
    val resultFlow: StateFlow<Any> = _result.asStateFlow()

    internal val _error = MutableStateFlow(null)
    val errorFlow: StateFlow<Any> = _error.asStateFlow()

    fun reset() {
        _result.value = null
        _error.value = null
    }
}

// ===== MODULE PROPERTIES END =====




// ============================================================
// ViewModel
// Binding interface between composable UI and FlowGraph.
// User-editable section below — preserved across regenerations.
// ============================================================

/**
 * ViewModel for the UserProfiles composable.
 * Bridges FlowGraph domain logic with Compose UI.
 *
 * @param controller The UserProfilesControllerInterface that manages FlowGraph execution
 * @generated by CodeNodeIO RuntimeViewModelGenerator
 */
class UserProfilesViewModel(
    private val controller: UserProfilesControllerInterface
) : ViewModel() {

    // Observable state from module properties
    val result: StateFlow<Any> = UserProfilesState.resultFlow
    val error: StateFlow<Any> = UserProfilesState.errorFlow

    // Execution state from controller
    val executionState: StateFlow<ExecutionState> = controller.executionState

    // Control methods
    fun start(): FlowGraph = controller.start()

    fun stop(): FlowGraph = controller.stop()

    fun reset(): FlowGraph = controller.reset()

    fun pause(): FlowGraph = controller.pause()

    fun resume(): FlowGraph = controller.resume()
}

