/*
 * StopWatchViewModel
 * Generated by CodeNodeIO RuntimeViewModelGenerator
 * License: Apache 2.0
 */

package io.codenode.stopwatch

import androidx.lifecycle.ViewModel
import io.codenode.fbpdsl.model.ExecutionState
import io.codenode.fbpdsl.model.FlowGraph
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import io.codenode.stopwatch.generated.StopWatchControllerInterface

// ===== MODULE PROPERTIES START =====
// Auto-generated from source output ports and sink input ports. Do not edit this section manually.
// Changes here will be overwritten on next code generation.

object StopWatchState {

    internal val _elapsedSeconds = MutableStateFlow(0)
    val elapsedSecondsFlow: StateFlow<Int> = _elapsedSeconds.asStateFlow()

    internal val _elapsedMinutes = MutableStateFlow(0)
    val elapsedMinutesFlow: StateFlow<Int> = _elapsedMinutes.asStateFlow()

    internal val _seconds = MutableStateFlow(0)
    val secondsFlow: StateFlow<Int> = _seconds.asStateFlow()

    internal val _minutes = MutableStateFlow(0)
    val minutesFlow: StateFlow<Int> = _minutes.asStateFlow()

    fun reset() {
        _elapsedSeconds.value = 0
        _elapsedMinutes.value = 0
        _seconds.value = 0
        _minutes.value = 0
    }
}

// ===== MODULE PROPERTIES END =====









// ============================================================
// ViewModel
// Binding interface between composable UI and FlowGraph.
// User-editable section below — preserved across regenerations.
// ============================================================

/**
 * ViewModel for the StopWatch composable.
 * Bridges FlowGraph domain logic with Compose UI.
 *
 * @param controller The StopWatchControllerInterface that manages FlowGraph execution
 * @generated by CodeNodeIO RuntimeViewModelGenerator
 */
class StopWatchViewModel(
    private val controller: StopWatchControllerInterface
) : ViewModel() {

    // Observable state from module properties
    val seconds: StateFlow<Int> = StopWatchState.secondsFlow
    val minutes: StateFlow<Int> = StopWatchState.minutesFlow

    // Execution state from controller
    val executionState: StateFlow<ExecutionState> = controller.executionState

    // Control methods
    fun start(): FlowGraph = controller.start()

    fun stop(): FlowGraph = controller.stop()

    fun reset(): FlowGraph = controller.reset()

    fun pause(): FlowGraph = controller.pause()

    fun resume(): FlowGraph = controller.resume()
}
