/*
 * Flow Graph: StopWatch
 * Version: 1.0.0
 * Description: Virtual circuit demo for stopwatch functionality
 *
 * This FlowGraph demonstrates the "virtual circuit" concept by implementing
 * a stopwatch using FBP (Flow-Based Programming) architecture:
 *
 * - TimerEmitter: Generic in0out2 node that emits elapsed seconds/minutes at tick intervals
 * - DisplayReceiver: Generic in2out0 node that receives time values for UI rendering
 *
 * Both nodes use Generic node types with custom port names and _useCaseClass configuration
 * to link to their ProcessingLogic implementations.
 *
 * The speedAttenuation config controls the tick interval (1000ms = 1 second)
 *
 * Generated by CodeNodeIO ModuleSaveService
 * License: Apache 2.0
 */

package io.codenode.stopwatch


import io.codenode.fbpdsl.dsl.*
import io.codenode.fbpdsl.model.*

val stopWatchFlowGraph = flowGraph("StopWatch", version = "1.0.0", description = "Virtual circuit demo for stopwatch functionality") {
    // Target Platforms
    targetPlatform(FlowGraph.TargetPlatform.KMP_ANDROID)
    targetPlatform(FlowGraph.TargetPlatform.KMP_IOS)
    targetPlatform(FlowGraph.TargetPlatform.KMP_DESKTOP)

    // Nodes
    val timerEmitter = codeNode("TimerEmitter", nodeType = "GENERIC") {
        position(100.0, 100.0)
        output("elapsedSeconds", Int::class)
        output("elapsedMinutes", Int::class)
        config("_genericType", "in0out2")
        config("speedAttenuation", "1000")
        config("_useCaseClass", "io.codenode.stopwatch.usecases.TimerEmitterComponent")
    }

    val displayReceiver = codeNode("DisplayReceiver", nodeType = "GENERIC") {
        position(400.0, 100.0)
        input("seconds", Int::class)
        input("minutes", Int::class)
        config("_genericType", "in2out0")
        config("_useCaseClass", "io.codenode.stopwatch.usecases.DisplayReceiverComponent")
    }

    // Connections
    timerEmitter.output("elapsedSeconds") connect displayReceiver.input("seconds")
    timerEmitter.output("elapsedMinutes") connect displayReceiver.input("minutes")
}
