/*
 * DemoUIPreviewProvider — Registers DemoUI preview composables for the runtime panel
 * Generated by CodeNodeIO PreviewProviderGenerator
 * License: Apache 2.0
 */

package io.codenode.testmodule.userInterface

import io.codenode.testmodule.viewmodel.DemoUIViewModel
import io.codenode.previewapi.PreviewRegistry

/**
 * Provides preview composables that render DemoUI components,
 * driven by the RuntimeSession's ViewModel state.
 */
object DemoUIPreviewProvider {

    /**
     * Registers DemoUI preview composables with the PreviewRegistry.
     */
    fun register() {
        PreviewRegistry.register("DemoUI") { viewModel, modifier ->
            val vm = viewModel as DemoUIViewModel
            DemoUI(viewModel = vm, modifier = modifier)
        }
    }
}
