/*
 * DemoUIPreviewProvider — Registers DemoUI preview composables for the runtime panel
 * Generated by CodeNodeIO PreviewProviderGenerator
 * License: Apache 2.0
 */

package io.codenode.testmodule.userInterface

import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import io.codenode.testmodule.viewmodel.DemoUIViewModel
import io.codenode.previewapi.PreviewRegistry

/**
 * Provides preview composables that render DemoUI components,
 * driven by the RuntimeSession's ViewModel state.
 *
 * Per feature 087 / Design B, the registered lambda is the host-app
 * "ScreenRoot" seam: it collects `viewModel.state` as Compose state and
 * passes `viewModel::onEvent` to the pure two-parameter DemoUI Screen.
 */
object DemoUIPreviewProvider {

    /**
     * Registers DemoUI preview composables with the PreviewRegistry.
     */
    fun register() {
        PreviewRegistry.register("DemoUI") { viewModel, modifier ->
            val vm = viewModel as DemoUIViewModel
            val state by vm.state.collectAsState()
            DemoUI(state = state, onEvent = vm::onEvent, modifier = modifier)
        }
    }
}
