/*
 * XYCoords Composable
 * Generated by CodeNodeIO EntityUIGenerator
 * License: Apache 2.0
 */

package io.codenode.xycoordrepo.userInterface

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import io.codenode.xycoordrepo.viewmodel.XYCoordsEvent
import io.codenode.xycoordrepo.viewmodel.XYCoordsState
import io.codenode.xycoordrepo.iptypes.XYCoord

@Composable
fun XYCoords(
    state: XYCoordsState,
    onEvent: (XYCoordsEvent) -> Unit,
    modifier: Modifier = Modifier
) {
    // Repository emits `result` as `Any` at the FBP-graph level; the runtime
    // payload is the current list of entities. Cast at the UI boundary so the
    // rest of this composable can iterate it as a typed `List<XYCoord>`.
    @Suppress("UNCHECKED_CAST")
    val items = (state.result as? List<XYCoord>) ?: emptyList()
    var selectedId by remember { mutableStateOf<Long?>(null) }
    var showAddForm by remember { mutableStateOf(false) }
    var showUpdateForm by remember { mutableStateOf(false) }
    var showRemoveConfirmation by remember { mutableStateOf(false) }

    val selectedItem = items.find { it.id == selectedId }

    // Clear selection if the selected item was removed externally
    LaunchedEffect(items, selectedId) {
        if (selectedId != null && selectedItem == null) {
            selectedId = null
        }
    }

    if (showAddForm) {
        AddUpdateXYCoord(
            existingItem = null,
            onSave = { item ->
                onEvent(XYCoordsEvent.UpdateSave(item))
                showAddForm = false
            },
            onCancel = { showAddForm = false },
            modifier = modifier
        )
        return
    }

    if (showUpdateForm && selectedItem != null) {
        AddUpdateXYCoord(
            existingItem = selectedItem,
            onSave = { item ->
                onEvent(XYCoordsEvent.UpdateUpdate(item))
                showUpdateForm = false
                selectedId = null
            },
            onCancel = { showUpdateForm = false },
            modifier = modifier
        )
        return
    }

    Column(
        modifier = modifier.fillMaxSize().padding(16.dp)
    ) {
        Text(
            text = "XYCoords",
            style = MaterialTheme.typography.headlineMedium,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        // Header row
        XYCoordHeaderRow()
        HorizontalDivider()

        // List or empty state
        Box(modifier = Modifier.weight(1f)) {
            if (items.isEmpty()) {
                Text(
                    text = "No xYCoords yet",
                    style = MaterialTheme.typography.bodyLarge,
                    modifier = Modifier.align(Alignment.Center)
                )
            } else {
                LazyColumn(modifier = Modifier.fillMaxSize()) {
                    items(items, key = { it.id }) { item ->
                        XYCoordRow(
                            item = item,
                            isSelected = item.id == selectedId,
                            onClick = {
                                selectedId = if (selectedId == item.id) null else item.id
                            }
                        )
                    }
                }
            }
        }

        // Button row
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(top = 16.dp),
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            Button(onClick = { showAddForm = true }) {
                Text("Add")
            }
            Button(
                onClick = { showUpdateForm = true },
                enabled = selectedItem != null
            ) {
                Text("Update")
            }
            Button(
                onClick = { showRemoveConfirmation = true },
                enabled = selectedItem != null
            ) {
                Text("Remove")
            }
        }

        if (showRemoveConfirmation && selectedItem != null) {
            AlertDialog(
                onDismissRequest = { showRemoveConfirmation = false },
                title = { Text("Remove this item?") },
                text = { Text("Are you sure you want to remove this xYCoord?") },
                confirmButton = {
                    TextButton(onClick = {
                        onEvent(XYCoordsEvent.UpdateRemove(selectedItem))
                        selectedId = null
                        showRemoveConfirmation = false
                    }) {
                        Text("Confirm")
                    }
                },
                dismissButton = {
                    TextButton(onClick = { showRemoveConfirmation = false }) {
                        Text("Cancel")
                    }
                }
            )
        }
    }
}

@Composable
private fun XYCoordHeaderRow() {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp, vertical = 12.dp),
        horizontalArrangement = Arrangement.SpaceBetween,
        verticalAlignment = Alignment.CenterVertically
    ) {
        Text(
            text = "X",
            style = MaterialTheme.typography.labelLarge,
            modifier = Modifier.weight(1f)
        )
        Text(
            text = "Y",
            style = MaterialTheme.typography.labelLarge,
            modifier = Modifier.weight(1f).padding(horizontal = 8.dp)
        )
    }
}
