/*
 * EdgeArtFilterViewModel
 * Generated by CodeNodeIO RuntimeViewModelGenerator
 * License: Apache 2.0
 */

package io.codenode.edgeartfilter

import androidx.compose.ui.graphics.ImageBitmap
import androidx.lifecycle.ViewModel
import io.codenode.fbpdsl.model.ExecutionState
import io.codenode.fbpdsl.model.FlowGraph
import kotlinx.coroutines.flow.StateFlow
import io.codenode.edgeartfilter.generated.EdgeArtFilterControllerInterface

/**
 * ViewModel for the EdgeArtFilter composable.
 * Bridges FlowGraph domain logic with Compose UI.
 *
 * @param controller The EdgeArtFilterControllerInterface that manages FlowGraph execution
 * @generated by CodeNodeIO RuntimeViewModelGenerator
 */
class EdgeArtFilterViewModel(
    private val controller: EdgeArtFilterControllerInterface
) : ViewModel() {

    // Observable state from module properties
    val processedImage: StateFlow<ImageData?> = EdgeArtFilterState.processedImageFlow

    // Execution state from controller
    val executionState: StateFlow<ExecutionState> = controller.executionState

    // Control methods
    fun start(): FlowGraph = controller.start()

    fun stop(): FlowGraph = controller.stop()

    fun reset(): FlowGraph = controller.reset()

    fun pause(): FlowGraph = controller.pause()

    fun resume(): FlowGraph = controller.resume()

    /**
     * Called by the UI when the user selects an image via file chooser.
     * Loads the image into an ImageData and triggers the pipeline.
     */
    fun selectImage(bitmap: ImageBitmap, width: Int, height: Int, sourcePath: String) {
        val imageData = ImageData(
            bitmap = bitmap,
            width = width,
            height = height,
            metadata = mapOf("source" to sourcePath)
        )
        EdgeArtFilterState._selectedImage.value = imageData
    }
}
