/*
 * Build script for ExpenseApproval
 * Module: ExpenseApproval
 * Version: 1.0.0
 * Generated by CodeNodeIO ModuleGenerator
 * License: Apache 2.0
 */

plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization")
    id("org.jetbrains.compose")
    id("org.jetbrains.kotlin.plugin.compose")
    id("com.android.library")
}

object LocalVersions {
    const val compose = "1.7.3"
}

kotlin {
    jvm {
        compilations.all {
            kotlinOptions.jvmTarget = "17"
        }
    }

    androidTarget {
        compilations.all {
            kotlinOptions.jvmTarget = "17"
        }
    }

    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ExpenseApproval"
            isStatic = true
        }
    }

    // Use default hierarchy template for shared iOS source sets
    applyDefaultHierarchyTemplate()

    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation("io.codenode:fbpDsl")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0")
                // KMP-compatible lifecycle support (works on all platforms)
                implementation("org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose:2.8.0")
                // Compose Multiplatform — required by ExpenseApprovalScreen (feature 098 US1)
                implementation("org.jetbrains.compose.runtime:runtime:${LocalVersions.compose}")
                implementation("org.jetbrains.compose.foundation:foundation:${LocalVersions.compose}")
                implementation("org.jetbrains.compose.material:material:${LocalVersions.compose}")
                implementation("org.jetbrains.compose.material:material-icons-extended:${LocalVersions.compose}")
                implementation("org.jetbrains.compose.ui:ui:${LocalVersions.compose}")
            }
        }

        val jvmMain by getting {
            dependencies {
                implementation("io.codenode:preview-api")
            }
        }

        val commonTest by getting {
            dependencies {
                implementation(kotlin("test"))
            }
        }

        val androidMain by getting {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.0")
                // Compose preview tooling annotations (feature 098 US2 / research.md P-3)
                implementation("org.jetbrains.compose.ui:ui-tooling-preview:${LocalVersions.compose}")
            }
        }
    }
}

android {
    namespace = "io.codenode.generated.ExpenseApproval"
    compileSdk = 34

    defaultConfig {
        minSdk = 24
        targetSdk = 34
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
    }

    dependencies {
        debugImplementation("org.jetbrains.compose.ui:ui-tooling:${LocalVersions.compose}")
    }
}
