/*
 * XYCoordsSourceCodeNode — Source node for XYCoords UI inputs.
 * Generated by CodeNodeIO UIFBPSourceCodeNodeGenerator (feature 087 / Decision 8)
 * License: Apache 2.0
 */

package io.codenode.xycoordrepo.nodes

import io.codenode.fbpdsl.model.CodeNodeFactory
import io.codenode.fbpdsl.model.CodeNodeType
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.runtime.NodeRuntime
import io.codenode.fbpdsl.runtime.PortSpec
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.SharedFlow
import io.codenode.fbpdsl.runtime.ProcessResult3
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.launch

object XYCoordsSourceCodeNode : CodeNodeDefinition {
    override val name = "XYCoordsSource"
    override val category = CodeNodeType.SOURCE
    override val description = "Emits UI input values into the processing graph"
    override val inputPorts = emptyList<PortSpec>()
    override val outputPorts = listOf(
        PortSpec("save", Any::class),
        PortSpec("update", Any::class),
        PortSpec("remove", Any::class)
    )

    /** Default runtime: never-emitting sources. Safe for palette drops outside a UI-FBP runtime. */
    override fun createRuntime(name: String): NodeRuntime {
        val placeholders: Array<SharedFlow<*>> = Array(3) { MutableSharedFlow<Any?>() }
        return buildRuntime(name, placeholders)
    }

    /**
     * Returns a per-flow-graph CodeNodeDefinition wrapper that emits values from
     * [sources] (one SharedFlow per output port, declared order) onto the FBP
     * output channels. Decision 8 / Design B.
     */
    fun withSources(vararg sources: SharedFlow<*>): CodeNodeDefinition =
        object : CodeNodeDefinition by this {
            override fun createRuntime(name: String): NodeRuntime = buildRuntime(name, sources)
        }

    @Suppress("UNCHECKED_CAST")
    private fun buildRuntime(name: String, sources: Array<out SharedFlow<*>>): NodeRuntime {
        return CodeNodeFactory.createSourceOut3<Any, Any, Any>(
            name = name,
            generate = { emit ->
                coroutineScope {
                    launch {
                        (sources[0] as SharedFlow<Any>).collect { value ->
                            emit(ProcessResult3(value, null, null))
                        }
                    }
                    launch {
                        (sources[1] as SharedFlow<Any>).collect { value ->
                            emit(ProcessResult3(null, value, null))
                        }
                    }
                    launch {
                        (sources[2] as SharedFlow<Any>).collect { value ->
                            emit(ProcessResult3(null, null, value))
                        }
                    }
                }
            }
        )
    }
}
