/*
 * XYCoordRepositoryCodeNode - Self-contained processor node for CRUD persistence
 * Generated by CodeNodeIO EntityRepositoryCodeNodeGenerator
 * License: Apache 2.0
 */

package io.codenode.xycoordrepo.nodes

import io.codenode.fbpdsl.model.CodeNodeFactory
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.model.CodeNodeType
import io.codenode.fbpdsl.runtime.NodeRuntime
import io.codenode.fbpdsl.runtime.PortSpec
import io.codenode.fbpdsl.runtime.ProcessResult2
import kotlinx.coroutines.flow.first
import io.codenode.persistence.xycoord.XYCoordRepository
import io.codenode.xycoordrepo.XYCoordsPersistence
import io.codenode.xycoordrepo.iptypes.XYCoord
import io.codenode.xycoordrepo.toEntity
import io.codenode.xycoordrepo.toXYCoord

/**
 * Processor node that performs CRUD operations on xycoords.
 *
 * Uses In3AnyOut2 pattern (fires on ANY input change). Per-channel identity
 * tracking prevents stale cached values from re-triggering operations.
 * Accesses DAO via XYCoordsPersistence (Koin).
 */
object XYCoordRepositoryCodeNode : CodeNodeDefinition {
    override val name = "XYCoordRepository"
    override val category = CodeNodeType.TRANSFORMER
    override val description = "Performs save, update, and remove operations on xycoords"
    override val inputPorts = listOf(
        PortSpec("save", XYCoord::class),
        PortSpec("update", XYCoord::class),
        PortSpec("remove", XYCoord::class)
    )
    override val outputPorts = listOf(
        PortSpec("result", List::class),
        PortSpec("error", String::class)
    )
    override val anyInput = true

    override fun createRuntime(name: String): NodeRuntime {
        val defaultEntity = XYCoord(X = 0.0, Y = 0.0)
        var lastSaveRef: XYCoord = defaultEntity
        var lastUpdateRef: XYCoord = defaultEntity
        var lastRemoveRef: XYCoord = defaultEntity

        return CodeNodeFactory.createIn3AnyOut2Processor<XYCoord, XYCoord, XYCoord, List<XYCoord>, String>(
            name = name,
            initialValue1 = defaultEntity,
            initialValue2 = defaultEntity,
            initialValue3 = defaultEntity,
            process = { save, update, remove ->
                try {
                    val repo = XYCoordRepository(XYCoordsPersistence.dao)
                    val isFreshSave = save !== lastSaveRef
                    val isFreshUpdate = update !== lastUpdateRef
                    val isFreshRemove = remove !== lastRemoveRef

                    suspend fun emitCurrentList(): ProcessResult2<List<XYCoord>, String> {
                        val list = repo.observeAll().first().map { it.toXYCoord() }
                        return ProcessResult2.first(list)
                    }

                    when {
                        isFreshSave -> {
                            lastSaveRef = save
                            repo.save(save.toEntity())
                            emitCurrentList()
                        }
                        isFreshUpdate -> {
                            lastUpdateRef = update
                            repo.update(update.toEntity())
                            emitCurrentList()
                        }
                        isFreshRemove -> {
                            lastRemoveRef = remove
                            repo.remove(remove.toEntity())
                            emitCurrentList()
                        }
                        else -> ProcessResult2(null, null)
                    }
                } catch (e: Exception) {
                    ProcessResult2.second("Error: ${e.message}")
                }
            }
        )
    }
}
