/*
 * XYCoordsSinkCodeNode — Sink node for XYCoords UI display.
 * Generated by CodeNodeIO UIFBPSinkCodeNodeGenerator (feature 087 / Decision 8)
 * License: Apache 2.0
 */

package io.codenode.xycoordrepo.nodes

import io.codenode.fbpdsl.model.CodeNodeFactory
import io.codenode.fbpdsl.model.CodeNodeType
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.runtime.NodeRuntime
import io.codenode.fbpdsl.runtime.PortSpec

object XYCoordsSinkCodeNode : CodeNodeDefinition {
    override val name = "XYCoordsSink"
    override val category = CodeNodeType.SINK
    override val description = "Receives processed results for XYCoords UI display"
    override val inputPorts = listOf(
        PortSpec("result", Any::class),
        PortSpec("error", Any::class)
    )
    override val outputPorts = emptyList<PortSpec>()

    /** Default runtime: no-op reporters. Safe for palette drops outside a UI-FBP runtime. */
    override fun createRuntime(name: String): NodeRuntime =
        buildRuntime(name, Array(2) { { _: Any? -> } })

    /**
     * Returns a per-flow-graph CodeNodeDefinition wrapper that delivers received
     * IPs to [reporters]. The Runtime factory passes one reporter per sinkInput,
     * in declared order. Decision 8 / Design B.
     */
    fun withReporters(vararg reporters: (Any?) -> Unit): CodeNodeDefinition =
        object : CodeNodeDefinition by this {
            override fun createRuntime(name: String): NodeRuntime =
                buildRuntime(name, reporters)
        }

    private fun buildRuntime(name: String, reporters: Array<out (Any?) -> Unit>): NodeRuntime {
        return CodeNodeFactory.createSinkIn2Any<Any, Any>(
            name = name,
            initialValue1 = "",
            initialValue2 = "",
            consume = { result, error ->
                reporters[0](result)
                reporters[1](error)
            }
        )
    }
}
