/*
 * GreeterSinkCodeNode — Sink node for Greeter UI display.
 * Generated by CodeNodeIO UIFBPSinkCodeNodeGenerator (feature 087 / Decision 8)
 * License: Apache 2.0
 */

package io.codenode.greeter.nodes

import io.codenode.fbpdsl.model.CodeNodeFactory
import io.codenode.fbpdsl.model.CodeNodeType
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.runtime.NodeRuntime
import io.codenode.fbpdsl.runtime.PortSpec

object GreeterSinkCodeNode : CodeNodeDefinition {
    override val name = "GreeterSink"
    override val category = CodeNodeType.SINK
    override val description = "Receives processed results for Greeter UI display"
    override val inputPorts = listOf(
        PortSpec("greeting", String::class),
        PortSpec("nameLength", Int::class)
    )
    override val outputPorts = emptyList<PortSpec>()

    /** Default runtime: no-op reporters. Safe for palette drops outside a UI-FBP runtime. */
    override fun createRuntime(name: String): NodeRuntime =
        buildRuntime(name, Array(2) { { _: Any? -> } })

    /**
     * Returns a per-flow-graph CodeNodeDefinition wrapper that delivers received
     * IPs to [reporters]. The Runtime factory passes one reporter per sinkInput,
     * in declared order. Decision 8 / Design B.
     */
    fun withReporters(vararg reporters: (Any?) -> Unit): CodeNodeDefinition =
        object : CodeNodeDefinition by this {
            override fun createRuntime(name: String): NodeRuntime =
                buildRuntime(name, reporters)
        }

    private fun buildRuntime(name: String, reporters: Array<out (Any?) -> Unit>): NodeRuntime {
        return CodeNodeFactory.createSinkIn2<String, Int>(
            name = name,
            consume = { greeting, nameLength ->
                reporters[0](greeting)
                reporters[1](nameLength)
            }
        )
    }
}
