/*
 * GreeterSourceCodeNode — Source node for Greeter UI inputs.
 * Generated by CodeNodeIO UIFBPSourceCodeNodeGenerator (feature 087 / Decision 8)
 * License: Apache 2.0
 */

package io.codenode.greeter.nodes

import io.codenode.fbpdsl.model.CodeNodeFactory
import io.codenode.fbpdsl.model.CodeNodeType
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.runtime.NodeRuntime
import io.codenode.fbpdsl.runtime.PortSpec
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.SharedFlow

object GreeterSourceCodeNode : CodeNodeDefinition {
    override val name = "GreeterSource"
    override val category = CodeNodeType.SOURCE
    override val description = "Emits UI input values into the processing graph"
    override val inputPorts = emptyList<PortSpec>()
    override val outputPorts = listOf(
        PortSpec("name", String::class)
    )

    /** Default runtime: never-emitting sources. Safe for palette drops outside a UI-FBP runtime. */
    override fun createRuntime(name: String): NodeRuntime {
        val placeholders: Array<SharedFlow<*>> = Array(1) { MutableSharedFlow<Any?>() }
        return buildRuntime(name, placeholders)
    }

    /**
     * Returns a per-flow-graph CodeNodeDefinition wrapper that emits values from
     * [sources] (one SharedFlow per output port, declared order) onto the FBP
     * output channels. Decision 8 / Design B.
     */
    fun withSources(vararg sources: SharedFlow<*>): CodeNodeDefinition =
        object : CodeNodeDefinition by this {
            override fun createRuntime(name: String): NodeRuntime = buildRuntime(name, sources)
        }

    @Suppress("UNCHECKED_CAST")
    private fun buildRuntime(name: String, sources: Array<out SharedFlow<*>>): NodeRuntime {
        return CodeNodeFactory.createContinuousSource<String>(
            name = name,
            generate = { emit ->
                (sources[0] as SharedFlow<String>).collect { value -> emit(value) }
            }
        )
    }
}
