/*
 * DemoUIState
 * Generated by CodeNodeIO UIFBPStateGenerator (feature 087 / Design B)
 * License: Apache 2.0
 */

package io.codenode.testmodule.viewmodel

import io.codenode.testmodule.iptypes.CalculationResults

data class DemoUIState(
    val results: CalculationResults? = null
)
