/*
 * DemoUIEvent
 * Generated by CodeNodeIO UIFBPEventGenerator (feature 087 / FR-002)
 * License: Apache 2.0
 */

package io.codenode.testmodule.viewmodel

sealed interface DemoUIEvent {
    data class UpdateA(val value: Double) : DemoUIEvent
    data class UpdateB(val value: Double) : DemoUIEvent
    data class UpdateC(val value: Double) : DemoUIEvent
}
