/*
 * DemoUIViewModel
 * Generated by CodeNodeIO UIFBPViewModelGenerator (feature 087 / Design B)
 * License: Apache 2.0
 */

package io.codenode.testmodule.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import io.codenode.fbpdsl.model.ExecutionState
import io.codenode.fbpdsl.model.FlowGraph
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import io.codenode.testmodule.controller.DemoUIControllerInterface
import io.codenode.testmodule.iptypes.CalculationResults

class DemoUIViewModel(
    private val controller: DemoUIControllerInterface
) : ViewModel() {

    private val _state = MutableStateFlow(DemoUIState())
    val state: StateFlow<DemoUIState> = _state.asStateFlow()

    val executionState: StateFlow<ExecutionState> = controller.executionState

    init {
        viewModelScope.launch {
            controller.results.collect { value ->
                _state.update { it.copy(results = value) }
            }
        }
    }

    fun onEvent(event: DemoUIEvent) {
        when (event) {
            is DemoUIEvent.UpdateA -> controller.emitA(event.value)
            is DemoUIEvent.UpdateB -> controller.emitB(event.value)
            is DemoUIEvent.UpdateC -> controller.emitC(event.value)
        }
    }

    fun start(): FlowGraph = controller.start()
    fun stop(): FlowGraph = controller.stop()
    fun pause(): FlowGraph = controller.pause()
    fun resume(): FlowGraph = controller.resume()
    fun reset(): FlowGraph = controller.reset()
}
