/*
 * DemoUIViewModel
 * Generated by CodeNodeIO UIFBPViewModelGenerator
 * License: Apache 2.0
 */

package io.codenode.testmodule.viewmodel

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import io.codenode.fbpdsl.model.ExecutionState
import io.codenode.fbpdsl.model.FlowGraph
import kotlinx.coroutines.flow.StateFlow
import io.codenode.testmodule.controller.DemoUIControllerInterface
import io.codenode.testmodule.iptypes.CalculationResults

class DemoUIViewModel(
    private val controller: DemoUIControllerInterface
) : ViewModel() {

    val results: StateFlow<CalculationResults?> = DemoUIState.resultsFlow
    val executionState: StateFlow<ExecutionState> = controller.executionState

    var state by mutableStateOf(DemoUIStateMVI())
        private set

    fun onAction(action: DemoUIAction) {
        when(action) {
            DemoUIAction.Emit -> emitMVI(state.A, state.B)

        }
    }

    fun emitMVI(a: Double, b: Double) {
        state.A = a
        DemoUIState._b.value = b
    }
    fun emit(a: Double, b: Double, c: Double) {
        DemoUIState._a.value = a
        DemoUIState._b.value = b
        DemoUIState._c.value = c
    }

    fun start(): FlowGraph = controller.start()
    fun stop(): FlowGraph = controller.stop()
    fun pause(): FlowGraph = controller.pause()
    fun resume(): FlowGraph = controller.resume()
    fun reset(): FlowGraph = controller.reset()
}
