/*
 * StopWatchControllerInterface
 * Generated by CodeNodeIO RuntimeControllerInterfaceGenerator
 * License: Apache 2.0
 */

package io.codenode.stopwatch.controller

import io.codenode.fbpdsl.model.FlowGraph
import io.codenode.fbpdsl.runtime.ModuleController
import kotlinx.coroutines.flow.StateFlow

/**
 * Interface defining the contract for StopWatch controllers.
 *
 * Enables dependency injection and testing by allowing
 * both the real controller and test fakes to be used.
 *
 * Extends [ModuleController] (feature 085 — universal-runtime collapse) so
 * consumers reach setAttenuationDelay/observers/getStatus through this typed
 * surface without casting to a concrete controller class.
 *
 * @generated by CodeNodeIO RuntimeControllerInterfaceGenerator
 */
interface StopWatchControllerInterface : ModuleController {
    val elapsedSeconds: StateFlow<Int>
    val elapsedMinutes: StateFlow<Int>
    val seconds: StateFlow<Int>
    val minutes: StateFlow<Int>
}
