/*
 * StopWatchRuntime — Universal-runtime factory for the StopWatch module
 * Generated by CodeNodeIO ModuleRuntimeGenerator
 * License: Apache 2.0
 */

package io.codenode.stopwatch.controller

import io.codenode.fbpdsl.model.FlowGraph
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.runtime.DynamicPipelineController
import io.codenode.fbpdsl.runtime.ModuleController
import io.codenode.stopwatch.viewmodel.StopWatchState
import io.codenode.stopwatch.nodes.DisplayReceiverCodeNode
import io.codenode.stopwatch.nodes.TimeIncrementerCodeNode
import io.codenode.stopwatch.nodes.TimerEmitterCodeNode

/**
 * Module-local lookup for resolving node names to compiled CodeNodeDefinitions.
 * Used by [DynamicPipelineController] when running this module without the GraphEditor.
 */
object StopWatchNodeRegistry {
    fun lookup(name: String): CodeNodeDefinition? = when (name) {
        "TimerEmitter" -> TimerEmitterCodeNode
        "TimeIncrementer" -> TimeIncrementerCodeNode
        "DisplayReceiver" -> DisplayReceiverCodeNode
        else -> null
    }
}

/**
 * Constructs a StopWatchControllerInterface backed by [DynamicPipelineController].
 *
 * Production-app consumers call this directly. The returned object delegates
 * every [ModuleController] member to the underlying controller and reads typed
 * state flows directly from StopWatchState.
 */
fun createStopWatchRuntime(flowGraph: FlowGraph): StopWatchControllerInterface {
    val controller = DynamicPipelineController(
        flowGraphProvider = { flowGraph },
        lookup = StopWatchNodeRegistry::lookup,
        onReset = StopWatchState::reset
    )
    return object : StopWatchControllerInterface, ModuleController by controller {
        override val elapsedSeconds = StopWatchState.elapsedSecondsFlow
        override val elapsedMinutes = StopWatchState.elapsedMinutesFlow
        override val seconds = StopWatchState.secondsFlow
        override val minutes = StopWatchState.minutesFlow
    }
}
