/*
 * XYCoordsRuntime — per-flow-graph factory for the XYCoords UI-FBP module.
 * Generated by CodeNodeIO UIFBPInterfaceGenerator (feature 087 / Design B)
 * License: Apache 2.0
 */

package io.codenode.xycoordrepo.controller

import io.codenode.fbpdsl.model.FlowGraph
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.runtime.DynamicPipelineController
import io.codenode.fbpdsl.runtime.ModuleController
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import io.codenode.xycoordrepo.nodes.XYCoordsSourceCodeNode
import io.codenode.xycoordrepo.nodes.XYCoordsSinkCodeNode

/**
 * Constructs a XYCoordsControllerInterface backed by [DynamicPipelineController].
 * Per-flow-graph state lives in this function's closure — multiple
 * concurrent calls produce fully isolated controllers.
 *
 * @param fallbackLookup Resolves CodeNodeDefinitions for nodes other than
 *        the generated XYCoordsSourceCodeNode / XYCoordsSinkCodeNode wrappers (e.g., transformers,
 *        intermediate processors). The Runtime Preview path passes the
 *        NodeDefinitionRegistry-backed lookup here so any CodeNode added
 *        to the canvas resolves. Defaults to no-fallback for direct callers.
 */
fun createXYCoordsRuntime(
    flowGraph: FlowGraph,
    fallbackLookup: (String) -> CodeNodeDefinition? = { null }
): XYCoordsControllerInterface {
    val _result = MutableStateFlow<Any?>(null)
    val _error = MutableStateFlow<Any?>(null)
    val _save = MutableSharedFlow<Any>(replay = 1, extraBufferCapacity = 64)
    val _update = MutableSharedFlow<Any>(replay = 1, extraBufferCapacity = 64)
    val _remove = MutableSharedFlow<Any>(replay = 1, extraBufferCapacity = 64)

    val sinkWrapper = XYCoordsSinkCodeNode.withReporters(
        { value -> _result.value = value as Any? },
        { value -> _error.value = value as Any? }
    )
    val sourceWrapper = XYCoordsSourceCodeNode.withSources(_save, _update, _remove)

    val controller = DynamicPipelineController(
        flowGraphProvider = { flowGraph },
        lookup = { nodeName -> when (nodeName) {
            "XYCoordsSource" -> sourceWrapper
            "XYCoordsSink" -> sinkWrapper
            else -> fallbackLookup(nodeName)
        } },
        onReset = {
            _result.value = null
            _error.value = null
        }
    )

    return object : XYCoordsControllerInterface, ModuleController by controller {
        override val result: StateFlow<Any?> = _result.asStateFlow()
        override val error: StateFlow<Any?> = _error.asStateFlow()
        override fun emitSave(value: Any) {
            controller.coroutineScope?.launch { _save.emit(value) }
        }
        override fun emitUpdate(value: Any) {
            controller.coroutineScope?.launch { _update.emit(value) }
        }
        override fun emitRemove(value: Any) {
            controller.coroutineScope?.launch { _remove.emit(value) }
        }
    }
}
