/*
 * XYCoordConverters - Conversion extensions between IP type and persistence entity
 * Generated by CodeNodeIO EntityConverterGenerator
 * License: Apache 2.0
 */

package io.codenode.xycoordrepo

import io.codenode.xycoordrepo.iptypes.XYCoord
import io.codenode.persistence.xycoord.XYCoordEntity

/** Convert IP type to persistence entity */
fun XYCoord.toEntity() = XYCoordEntity(id = id, X = X, Y = Y)

/** Convert persistence entity to IP type */
fun XYCoordEntity.toXYCoord() = XYCoord(id = id, X = X, Y = Y)
