/*
 * EdgeArtFilter Flow
 * Generated by CodeNodeIO RuntimeFlowGenerator
 * License: Apache 2.0
 */

package io.codenode.edgeartfilter.flow

import io.codenode.edgeartfilter.EdgeArtFilterState
import io.codenode.edgeartfilter.iptypes.ImageData
import io.codenode.edgeartfilter.nodes.ImagePickerCodeNode
import io.codenode.edgeartfilter.nodes.GrayscaleTransformerCodeNode
import io.codenode.edgeartfilter.nodes.EdgeDetectorCodeNode
import io.codenode.edgeartfilter.nodes.ColorOverlayCodeNode
import io.codenode.edgeartfilter.nodes.ImageViewerCodeNode

import io.codenode.fbpdsl.runtime.In2Out1Runtime
import io.codenode.fbpdsl.runtime.SinkRuntime
import io.codenode.fbpdsl.runtime.SourceOut2Runtime
import io.codenode.fbpdsl.runtime.TransformerRuntime
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.StateFlow

/**
 * Flow orchestrator for: EdgeArtFilter
 *
 * Version: 2.0.0 — uses self-contained CodeNodeDefinition objects
 *
 * Nodes: 5
 * Connections: 5 (including fan-out from ImagePicker)
 *
 * @generated by CodeNodeIO RuntimeFlowGenerator
 */
class EdgeArtFilterFlow {

    // Observable state delegated from module state
    val processedImageFlow: StateFlow<ImageData?> = EdgeArtFilterState.processedImageFlow

    // Runtime instances created from self-contained CodeNodeDefinitions

    /**
     * ImagePicker: Source with 2 outputs (fan-out)
     *   outputChannel1 → GrayscaleTransformer.inputChannel (edge detection path)
     *   outputChannel2 → ColorOverlay.inputChannel1 (original image for merging)
     */
    @Suppress("UNCHECKED_CAST")
    internal val imagePicker = ImagePickerCodeNode.createRuntime("ImagePicker") as SourceOut2Runtime<ImageData, ImageData>

    /**
     * GrayscaleTransformer: 1-input, 1-output transformer
     *   inputChannel ← ImagePicker.outputChannel1
     *   outputChannel → EdgeDetector.inputChannel
     */
    @Suppress("UNCHECKED_CAST")
    internal val grayscaleTransformer = GrayscaleTransformerCodeNode.createRuntime("GrayscaleTransformer") as TransformerRuntime<ImageData, ImageData>

    /**
     * EdgeDetector: 1-input, 1-output transformer
     *   inputChannel ← GrayscaleTransformer.outputChannel
     *   outputChannel → ColorOverlay.inputChannel2
     */
    @Suppress("UNCHECKED_CAST")
    internal val edgeDetector = EdgeDetectorCodeNode.createRuntime("EdgeDetector") as TransformerRuntime<ImageData, ImageData>

    /**
     * ColorOverlay: 2-input, 1-output processor
     *   inputChannel1 ← ImagePicker.outputChannel2 (original image)
     *   inputChannel2 ← EdgeDetector.outputChannel (edge map)
     *   outputChannel → ImageViewer.inputChannel
     */
    @Suppress("UNCHECKED_CAST")
    internal val colorOverlay = ColorOverlayCodeNode.createRuntime("ColorOverlay") as In2Out1Runtime<ImageData, ImageData, ImageData>

    /**
     * ImageViewer: Sink node
     *   inputChannel ← ColorOverlay.outputChannel
     */
    @Suppress("UNCHECKED_CAST")
    internal val imageViewer = ImageViewerCodeNode.createRuntime("ImageViewer") as SinkRuntime<ImageData>

    /**
     * Starts the flow with the given coroutine scope.
     */
    suspend fun start(scope: CoroutineScope) {
        imagePicker.start(scope) {}
        wireConnections()
        grayscaleTransformer.start(scope) {}
        edgeDetector.start(scope) {}
        colorOverlay.start(scope) {}
        imageViewer.start(scope) {}
    }

    /**
     * Stops all runtime instances.
     */
    fun stop() {
        imagePicker.stop()
        grayscaleTransformer.stop()
        edgeDetector.stop()
        colorOverlay.stop()
        imageViewer.stop()
    }

    /**
     * Resets all observable state.
     */
    fun reset() {
        EdgeArtFilterState.reset()
    }

    /**
     * Wires connections between runtime instances.
     *
     * Fan-out: ImagePicker sends the same data to both
     * GrayscaleTransformer (channel1) and ColorOverlay (channel2).
     */
    fun wireConnections() {
        // ImagePicker fan-out (SourceOut2Runtime owns Channel objects — direct assignment)
        grayscaleTransformer.inputChannel = imagePicker.outputChannel1
        colorOverlay.inputChannel1 = imagePicker.outputChannel2

        // Edge detection path: GrayscaleTransformer → EdgeDetector
        // TransformerRuntime output is SendChannel, so create intermediate Channel
        val grayscaleToEdge = Channel<ImageData>(Channel.BUFFERED)
        grayscaleTransformer.outputChannel = grayscaleToEdge
        edgeDetector.inputChannel = grayscaleToEdge

        // EdgeDetector → ColorOverlay (fan-in)
        val edgeToOverlay = Channel<ImageData>(Channel.BUFFERED)
        edgeDetector.outputChannel = edgeToOverlay
        colorOverlay.inputChannel2 = edgeToOverlay

        // ColorOverlay → ImageViewer
        // In2Out1Runtime output is SendChannel, so create intermediate Channel
        val overlayToViewer = Channel<ImageData>(Channel.BUFFERED)
        colorOverlay.outputChannel = overlayToViewer
        imageViewer.inputChannel = overlayToViewer
    }
}
