/*
 * GraphNode Template: EALogic
 * @GraphNodeTemplate
 * @TemplateName EALogic
 * @Description Grouped from 4 nodes
 * @InputPorts 1
 * @OutputPorts 1
 * @ChildNodes 4
 * Created: 2026-06-23T09:04:42.253649
 * License: Apache 2.0
 */

package io.codenode.expenseapproval.graphnodes

import io.codenode.fbpdsl.dsl.*
import io.codenode.fbpdsl.model.*
import io.codenode.fbpdsl.runtime.*
import io.codenode.expenseapproval.iptypes.*

val eALogicGraphNode: GraphNode = graphNode("EALogic") {
    description = "Grouped from 4 nodes"
    position(420.0, 300.0)

    // Child nodes
    val child_approve = codeNode("Approve") {
        position(290.0, 50.0)
        input("amount", Any::class)
        output("decision", Any::class)
        config("_genericType", "in1out1")
        config("_codeNodeDefinition", "true")
        config("_codeNodeClass", "io.codenode.expenseapproval.nodes.ApproveCodeNode")
    }

    val child_escalate_1 = codeNode("Escalate") {
        position(290.0, 290.0)
        input("amount", Any::class)
        output("decision", Any::class)
        config("_genericType", "in1out1")
        config("_codeNodeDefinition", "true")
        config("_codeNodeClass", "io.codenode.expenseapproval.nodes.EscalateCodeNode")
    }

    val child_mergedecision_2 = codeNode("MergeDecision", nodeType = "MERGER") {
        position(530.0, 170.0)
        input("input1", Any::class)
        input("input2", Any::class)
        output("output1", Any::class)
        config("_genericType", "in2out1")
        config("_codeNodeDefinition", "true")
        config("_codeNodeClass", "io.codenode.expenseapproval.nodes.MergeDecisionCodeNode")
    }

    val child_conditionbranch_3 = codeNode("ConditionBranch") {
        position(50.0, 170.0)
        input("amount", Any::class)
        output("approved", Any::class)
        output("escalated", Any::class)
        config("_genericType", "in1out2")
        config("_codeNodeDefinition", "true")
        config("_codeNodeClass", "io.codenode.expenseapproval.nodes.ConditionBranchCodeNode")
    }

    // Internal connections
    internalConnection(child_conditionbranch_3, "approved", child_approve, "amount") withType "ip_expenseamount"
    internalConnection(child_conditionbranch_3, "escalated", child_escalate_1, "amount") withType "ip_expenseamount"
    internalConnection(child_approve, "decision", child_mergedecision_2, "input1") withType "ip_approvaldecision"
    internalConnection(child_escalate_1, "decision", child_mergedecision_2, "input2") withType "ip_approvaldecision"

    // Port mappings
    portMapping("out_mergedecision_output1", "child_mergedecision_2", "output1")
    portMapping("in_conditionbranch_amount", "child_conditionbranch_3", "amount")

    // Exposed input ports
    exposeInput("in_conditionbranch_amount", ExpenseAmount::class)

    // Exposed output ports
    exposeOutput("out_mergedecision_output1", ApprovalDecision::class)
}


/**
 * Compiled GraphNodeDefinition for EALogic. Generated by
 * GraphNodeTemplateSerializer alongside the canvas-managed `eALogicGraphNode`
 * template val above. The companion META-INF/codenode/graphnode-definitions
 * resource lists this object's FQN so NodeDefinitionRegistry surfaces it
 * at workspace load + post-Recompile.
 */
internal object EALogicGraphNode : GraphNodeDefinition {
    override val name: String = "EALogic"
    override val category: GraphNodeCategory = GraphNodeCategory.GRAPH
    override val description: String? = "Grouped from 4 nodes"
    override val inputPorts: List<PortSpec> = listOf(PortSpec("in_conditionbranch_amount", ExpenseAmount::class))
    override val outputPorts: List<PortSpec> = listOf(PortSpec("out_mergedecision_output1", ApprovalDecision::class))

    override fun createRuntime(name: String, childLookup: (String) -> NodeDefinition?): GraphNodeRuntime =
        CompiledGraphNodeRuntime(name, eALogicGraphNode, childLookup)
}
