/*
 * GreeterPreviewProvider — Registers Greeter preview composables for the runtime panel
 * Generated by CodeNodeIO PreviewProviderGenerator
 * License: Apache 2.0
 */

package io.codenode.greeter.userInterface

import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import io.codenode.greeter.viewmodel.GreeterViewModel
import io.codenode.previewapi.PreviewRegistry

/**
 * Provides preview composables that render Greeter components,
 * driven by the RuntimeSession's ViewModel state.
 *
 * Per feature 087 / Design B, the registered lambda is the host-app
 * "ScreenRoot" seam: it collects `viewModel.state` as Compose state and
 * passes `viewModel::onEvent` to the pure two-parameter Greeter Screen.
 */
object GreeterPreviewProvider {

    /**
     * Registers Greeter preview composables with the PreviewRegistry.
     */
    fun register() {
        PreviewRegistry.register("Greeter") { viewModel, modifier ->
            val vm = viewModel as GreeterViewModel
            val state by vm.state.collectAsState()
            Greeter(state = state, onEvent = vm::onEvent, modifier = modifier)
        }
    }
}
