/*
 * CircuitViewModelInternals — Feature 109 generated shared helper types
 * Generated by CodeNodeIO CircuitViewModelInternalsGenerator
 * License: Apache 2.0
 */

package io.codenode.expenseapproval.viewmodel

/** Per-input-port form-field draft values, keyed by property name. */
internal data class FormFieldsSlot(val values: Map<String, String>)

/** Per-output-port most-recent IP. `null` until the first Sink arrival. */
internal data class LatestIpSlot(val ip: Any?)

/** Per-input-port runtime / error status. */
internal sealed interface RuntimeStatus {
    data object Idle : RuntimeStatus
    data object RuntimeNotActive : RuntimeStatus
    data class EmitError(val propertyName: String, val message: String) : RuntimeStatus
}

/**
 * Internal union of the public per-prefix Event surface plus generator-internal
 * [SinkArrival] dispatches. Prefix-agnostic — `Public.event` is `Any` so the
 * one shared declaration serves every circuit in the module. The per-prefix
 * reducer casts at the call site: `when (val e = event.event as <Prefix>Event)`.
 */
internal sealed interface ReducerEvent {
    data class Public(val event: Any) : ReducerEvent
    data class SinkArrival(val portId: String, val ip: Any?) : ReducerEvent
}
