/*
 * EALogicState
 * Generated by CodeNodeIO UIFBPStateGenerator (feature 087 / Design B)
 * License: Apache 2.0
 */

package io.codenode.expenseapproval.viewmodel

data class EALogicState(
    val out_mergedecision_output1: Any? = null
)
