/*
 * EALogicEvent
 * Generated by CodeNodeIO UIFBPEventGenerator (feature 087 / FR-002)
 * License: Apache 2.0
 */

package io.codenode.expenseapproval.viewmodel

sealed interface EALogicEvent {
    data class UpdateAmountChanged(val value: Any) : EALogicEvent
    data object SubmitClicked : EALogicEvent
}
