/*
 * EALogicViewModel
 * Generated by CodeNodeIO UIFBPViewModelGenerator (feature 087 / Design B)
 * License: Apache 2.0
 */

package io.codenode.expenseapproval.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import io.codenode.fbpdsl.model.ExecutionState
import io.codenode.fbpdsl.model.FlowGraph
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import io.codenode.expenseapproval.controller.EALogicControllerInterface

class EALogicViewModel(
    private val controller: EALogicControllerInterface
) : ViewModel() {

    private val _state = MutableStateFlow(EALogicState())
    val state: StateFlow<EALogicState> = _state.asStateFlow()

    val executionState: StateFlow<ExecutionState> = controller.executionState

    init {
        viewModelScope.launch {
            controller.amount.collect { value ->
                _state.update { it.copy(amount = value) }
            }
        }
        viewModelScope.launch {
            controller.status.collect { value ->
                _state.update { it.copy(status = value) }
            }
        }
        viewModelScope.launch {
            controller.approver.collect { value ->
                _state.update { it.copy(approver = value) }
            }
        }
    }

    fun onEvent(event: EALogicEvent) {
        when (event) {
            is EALogicEvent.UpdateAmountChanged -> controller.emitAmountChanged(event.value)
            EALogicEvent.SubmitClicked -> controller.emitSubmitClicked()
        }
    }

    fun start(): FlowGraph = controller.start()
    fun stop(): FlowGraph = controller.stop()
    fun pause(): FlowGraph = controller.pause()
    fun resume(): FlowGraph = controller.resume()
    fun reset(): FlowGraph = controller.reset()

    // ========== Type Conversion Bridging (FR-029) ==========
    // Add Screen ↔ FBP type converters here when Screen State / Event types
    // diverge from the FBP-side IP types declared in {Name}GraphNode.kt.
    // See feature 100 US6 spec.md FR-029 + research.md Decision D-US6-E for the
    // stub-based contract. Example pattern:
    //
    //     private fun stateAmountToExpenseAmount(amount: Double): ExpenseAmount {
    //         // TODO: implement Double → ExpenseAmount conversion
    //         return ExpenseAmount(amount)
    //     }
}
