/*
 * EALogicState
 * Generated by CodeNodeIO UIFBPStateGenerator (feature 087 / Design B)
 * License: Apache 2.0
 */

package io.codenode.expenseapproval.viewmodel

data class EALogicState(
    val amount: Any? = null,
    val status: ExpenseApprovalStatus? = null,
    val approver: Approver? = null
)
