/*
 * EALogicViewModel
 * Generated by CodeNodeIO UIFBPViewModelGenerator (feature 087 / Design B)
 * License: Apache 2.0
 */

package io.codenode.expenseapproval.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import io.codenode.fbpdsl.model.ExecutionState
import io.codenode.fbpdsl.model.FlowGraph
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import io.codenode.expenseapproval.controller.EALogicControllerInterface

class EALogicViewModel(
    private val controller: EALogicControllerInterface
) : ViewModel() {

    private val _state = MutableStateFlow(EALogicState())
    val state: StateFlow<EALogicState> = _state.asStateFlow()

    val executionState: StateFlow<ExecutionState> = controller.executionState

    init {
        viewModelScope.launch {
            controller.out_mergedecision_output1.collect { value ->
                _state.update { it.copy(out_mergedecision_output1 = value) }
            }
        }
    }

    fun onEvent(event: EALogicEvent) {
        when (event) {
            is EALogicEvent.UpdateIn_conditionbranch_amount -> controller.emitIn_conditionbranch_amount(event.value)
        }
    }

    fun start(): FlowGraph = controller.start()
    fun stop(): FlowGraph = controller.stop()
    fun pause(): FlowGraph = controller.pause()
    fun resume(): FlowGraph = controller.resume()
    fun reset(): FlowGraph = controller.reset()

    // ========== Type Conversion Bridging (FR-029) ==========
    // No bridging stubs needed — Screen State field types match the
    // FBP-side IP types declared in {Name}GraphNode.kt's exposeOutput calls,
    // OR `spec.screenStateFieldTypes` was not populated by the caller. Add
    // converters here manually if needed.
}
