/*
 * ExpenseApprovalLogicViewModel — Feature 103 generated Reducer + ViewModel for ExpenseApprovalLogic UI Draft
 * Generated by CodeNodeIO UIDraftReducerGenerator
 * License: Apache 2.0
 */

package io.codenode.expenseapproval.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import io.codenode.expenseapproval.nodes.ExpenseApprovalLogicSinkCodeNode
import io.codenode.expenseapproval.nodes.ExpenseApprovalLogicSourceCodeNode
import io.codenode.expenseapproval.iptypes.ExpenseAmount
import io.codenode.expenseapproval.iptypes.ApprovalDecision

/**
 * Owns the live [ExpenseApprovalLogicState] for ExpenseApprovalLogic UI Draft and serializes
 * event dispatch through [onEvent]. Per-input-port emit channels live on the imported
 * `<port>SourceCodeNode` singletons (FR-029 / C-GO9); per-output-port `latestIp` StateFlows
 * live on the imported `<port>SinkCodeNode` singletons (FR-030 / C-GO9). The ViewModel
 * pushes IPs into the Source singletons' `emitChannel` from `handleEmit` and observes the
 * Sink singletons' `latestIp` from `init` — `viewModelScope` owns those coroutines.
 */
internal open class ExpenseApprovalLogicViewModel : ViewModel() {

    private val _state: MutableStateFlow<ExpenseApprovalLogicState> = MutableStateFlow(ExpenseApprovalLogicState.initial())
    val state: StateFlow<ExpenseApprovalLogicState> = _state.asStateFlow()

    init {
        viewModelScope.launch {
            ExpenseApprovalLogicSinkCodeNode.latestIps.getValue("out_mergedecision_output1").collect { newIp ->
                _state.value = reduceExpenseApprovalLogic(_state.value, ReducerEvent.SinkArrival("ealogic_out_mergedecision_output1", newIp))
            }
        }
    }

    /** Dispatch entry — every user action routes through here. */
    fun onEvent(event: ExpenseApprovalLogicEvent) {
        when (event) {
            is ExpenseApprovalLogicEvent.OnFieldEdit -> {
                _state.value = reduceExpenseApprovalLogic(_state.value, ReducerEvent.Public(event))
            }
            is ExpenseApprovalLogicEvent.OnEmit -> handleEmit(event)
        }
    }

    /** Handle OnEmit: gate on runtime state, parse + assemble, push into the Source singleton's emitChannel. */
    private fun handleEmit(event: ExpenseApprovalLogicEvent.OnEmit) {
        val current = _state.value
        if (!isRuntimeRunning()) {
            // FR-028 — reject Emit when runtime is stopped or recompiling.
            _state.value = current.copy(
                runtimeStatus = current.runtimeStatus + (event.portId to RuntimeStatus.RuntimeNotActive)
            )
            return
        }
        when (event.portId) {
            "ealogic_in_conditionbranch_amount" -> {
                val current = _state.value
                val slot = current.formFields["ealogic_in_conditionbranch_amount"] ?: return
                val parsed = mutableMapOf<String, Any?>()
                run {
                    val raw = slot.values["amount"] ?: ""
                    val parsedValue: Any? = raw.toDoubleOrNull()
                    if (parsedValue == null) {
                        _state.value = current.copy(
                            runtimeStatus = current.runtimeStatus + ("ealogic_in_conditionbranch_amount" to RuntimeStatus.EmitError(
                                propertyName = "amount",
                                message = "Cannot parse '${raw}' as Double for property 'amount'",
                            ))
                        )
                        return
                    }
                    parsed["amount"] = parsedValue
                }
                ExpenseApprovalLogicSourceCodeNode.emitChannels.getValue("in_conditionbranch_amount").trySend(ExpenseAmount(amount = parsed["amount"] as Double))
                _state.value = current.copy(
                    runtimeStatus = current.runtimeStatus + ("ealogic_in_conditionbranch_amount" to RuntimeStatus.Idle)
                )
            }
            else -> Unit
        }
    }

    /**
     * Hook for runtime-state gating per FR-026 / FR-027 / FR-028. The host can override
     * this — for example, to check the active [io.codenode.flowgraphexecute.RuntimeSession]'s
     * executionState. Default returns `true` (RUNNING) so Runtime Preview can wire the
     * gate at instantiation time.
     */
    protected open fun isRuntimeRunning(): Boolean = true
}

/**
 * Pure Reducer: `(ExpenseApprovalLogicState, ReducerEvent) → ExpenseApprovalLogicState`. All I/O lives in the
 * ViewModel's `onEvent` / `handleEmit`; this function never touches a channel, a Sink,
 * or runtime-state. Same input → same output, always.
 */
internal fun reduceExpenseApprovalLogic(state: ExpenseApprovalLogicState, event: ReducerEvent): ExpenseApprovalLogicState =
    when (event) {
        is ReducerEvent.Public -> when (val e = event.event as ExpenseApprovalLogicEvent) {
            is ExpenseApprovalLogicEvent.OnFieldEdit -> {
                val slot = state.formFields[e.portId]
                    ?: FormFieldsSlot(values = emptyMap())
                val newSlot = slot.copy(values = slot.values + (e.propertyName to e.rawValue))
                // C-RB6 — any user edit clears prior RuntimeNotActive / EmitError status.
                state.copy(
                    formFields = state.formFields + (e.portId to newSlot),
                    runtimeStatus = state.runtimeStatus + (e.portId to RuntimeStatus.Idle),
                )
            }
            is ExpenseApprovalLogicEvent.OnEmit -> state // side-effecting; handled in ViewModel.handleEmit
        }
        is ReducerEvent.SinkArrival -> {
            state.copy(
                latestIps = state.latestIps + (event.portId to LatestIpSlot(ip = event.ip)),
            )
        }
    }

