/*
 * ExpenseApprovalLogicState — Feature 103 generated state for ExpenseApprovalLogic UI Draft
 * Generated by CodeNodeIO UIDraftStateGenerator
 * License: Apache 2.0
 */

package io.codenode.expenseapproval.viewmodel

/**
 * Single immutable snapshot of the ExpenseApprovalLogic UI Draft view state.
 * Updated only by the Reducer; read by the composable.
 */
internal data class ExpenseApprovalLogicState(
    val formFields: Map<String, FormFieldsSlot>,
    val latestIps: Map<String, LatestIpSlot>,
    val runtimeStatus: Map<String, RuntimeStatus>,
) {
    companion object {
        fun initial(): ExpenseApprovalLogicState = ExpenseApprovalLogicState(
            formFields = mapOf(
                "ealogic_in_conditionbranch_amount" to FormFieldsSlot(values = mapOf("amount" to "0")),
            ),
            latestIps = mapOf(
                "ealogic_out_mergedecision_output1" to LatestIpSlot(ip = null),
            ),
            runtimeStatus = mapOf(
                "ealogic_in_conditionbranch_amount" to RuntimeStatus.Idle,
            ),
        )
    }
}
