/*
 * UIDraftState — Feature 103 generated state for EALogic UI Draft
 * Generated by CodeNodeIO UIDraftStateGenerator
 * License: Apache 2.0
 */

package io.codenode.expenseapproval.viewmodel

/** Per-input-port form-field draft values, keyed by property name. */
internal data class FormFieldsSlot(val values: Map<String, String>)

/** Per-output-port most-recent IP. `null` until the first Sink arrival. */
internal data class LatestIpSlot(val ip: Any?)

/** Per-input-port runtime / error status. */
internal sealed interface RuntimeStatus {
    data object Idle : RuntimeStatus
    data object RuntimeNotActive : RuntimeStatus
    data class EmitError(val propertyName: String, val message: String) : RuntimeStatus
}

/**
 * Single immutable snapshot of the EALogic UI Draft view state.
 * Updated only by the Reducer; read by the composable.
 */
internal data class UIDraftState(
    val formFields: Map<String, FormFieldsSlot>,
    val latestIps: Map<String, LatestIpSlot>,
    val runtimeStatus: Map<String, RuntimeStatus>,
) {
    companion object {
        fun initial(): UIDraftState = UIDraftState(
            formFields = mapOf(
                "ealogic_in_conditionbranch_amount" to FormFieldsSlot(values = mapOf("amount" to "0")),
            ),
            latestIps = mapOf(
                "ealogic_out_mergedecision_output1" to LatestIpSlot(ip = null),
            ),
            runtimeStatus = mapOf(
                "ealogic_in_conditionbranch_amount" to RuntimeStatus.Idle,
            ),
        )
    }
}
