/*
 * UIDraftEvent — Feature 103 generated event surface for EALogic UI Draft
 * Generated by CodeNodeIO UIDraftEventGenerator
 * License: Apache 2.0
 */

package io.codenode.expenseapproval.viewmodel

/**
 * Public event surface dispatched from the composable to the Reducer via `onEvent`.
 * Per FR-023, only two variants exist — the port shape is conveyed at runtime via
 * `portId`, not encoded in the type system.
 */
internal sealed interface UIDraftEvent {
    /**
     * User edited a single field — typing into a TextField or toggling a Checkbox.
     *
     * @param portId Identifier of the input port whose composable owns this field.
     * @param propertyName Property name within the input port's IP-Type data class.
     * @param rawValue Raw string representation of the new value.
     *   - String properties: as typed.
     *   - Number properties: as typed (parse-on-Emit).
     *   - Boolean properties: `"true"` or `"false"` (Checkbox onCheckedChange).
     */
    data class OnFieldEdit(
        val portId: String,
        val propertyName: String,
        val rawValue: String,
    ) : UIDraftEvent

    /**
     * User pressed Emit on an input port — the Reducer reads `formFields[portId]`
     * from State, parses + assembles the IP, and dispatches it through the
     * corresponding Source CodeNode (subject to runtime-state gating per FR-026 – FR-028).
     */
    data class OnEmit(val portId: String) : UIDraftEvent
}
