/*
 * DemoUISinkCodeNode — Sink node for DemoUI UI display.
 * Generated by CodeNodeIO UIFBPSinkCodeNodeGenerator (feature 087 / Decision 8)
 * License: Apache 2.0
 */

package io.codenode.testmodule.nodes

import io.codenode.fbpdsl.model.CodeNodeFactory
import io.codenode.fbpdsl.model.CodeNodeType
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.runtime.NodeRuntime
import io.codenode.fbpdsl.runtime.PortSpec
import io.codenode.testmodule.iptypes.CalculationResults

object DemoUISinkCodeNode : CodeNodeDefinition {
    override val name = "DemoUISink"
    override val category = CodeNodeType.SINK
    override val description = "Receives processed results for DemoUI UI display"
    override val inputPorts = listOf(
        PortSpec("results", CalculationResults::class)
    )
    override val outputPorts = emptyList<PortSpec>()

    /** Default runtime: no-op reporters. Safe for palette drops outside a UI-FBP runtime. */
    override fun createRuntime(name: String): NodeRuntime =
        buildRuntime(name, Array(1) { { _: Any? -> } })

    /**
     * Returns a per-flow-graph CodeNodeDefinition wrapper that delivers received
     * IPs to [reporters]. The Runtime factory passes one reporter per sinkInput,
     * in declared order. Decision 8 / Design B.
     */
    fun withReporters(vararg reporters: (Any?) -> Unit): CodeNodeDefinition =
        object : CodeNodeDefinition by this {
            override fun createRuntime(name: String): NodeRuntime =
                buildRuntime(name, reporters)
        }

    private fun buildRuntime(name: String, reporters: Array<out (Any?) -> Unit>): NodeRuntime {
        return CodeNodeFactory.createContinuousSink<CalculationResults>(
            name = name,
            consume = { value -> reporters[0](value) }
        )
    }
}
