/*
 * DemoUISourceCodeNode — Source node for DemoUI UI inputs.
 * Generated by CodeNodeIO UIFBPSourceCodeNodeGenerator (feature 087 / Decision 8)
 * License: Apache 2.0
 */

package io.codenode.testmodule.nodes

import io.codenode.fbpdsl.model.CodeNodeFactory
import io.codenode.fbpdsl.model.CodeNodeType
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.runtime.NodeRuntime
import io.codenode.fbpdsl.runtime.PortSpec
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.SharedFlow
import io.codenode.fbpdsl.runtime.ProcessResult3
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.launch

object DemoUISourceCodeNode : CodeNodeDefinition {
    override val name = "DemoUISource"
    override val category = CodeNodeType.SOURCE
    override val description = "Emits UI input values into the processing graph"
    override val inputPorts = emptyList<PortSpec>()
    override val outputPorts = listOf(
        PortSpec("a", Double::class),
        PortSpec("b", Double::class),
        PortSpec("c", Double::class)
    )

    /** Default runtime: never-emitting sources. Safe for palette drops outside a UI-FBP runtime. */
    override fun createRuntime(name: String): NodeRuntime {
        val placeholders: Array<SharedFlow<*>> = Array(3) { MutableSharedFlow<Any?>() }
        return buildRuntime(name, placeholders)
    }

    /**
     * Returns a per-flow-graph CodeNodeDefinition wrapper that emits values from
     * [sources] (one SharedFlow per output port, declared order) onto the FBP
     * output channels. Decision 8 / Design B.
     */
    fun withSources(vararg sources: SharedFlow<*>): CodeNodeDefinition =
        object : CodeNodeDefinition by this {
            override fun createRuntime(name: String): NodeRuntime = buildRuntime(name, sources)
        }

    @Suppress("UNCHECKED_CAST")
    private fun buildRuntime(name: String, sources: Array<out SharedFlow<*>>): NodeRuntime {
        return CodeNodeFactory.createSourceOut3<Double, Double, Double>(
            name = name,
            generate = { emit ->
                val latest = arrayOfNulls<Any?>(3)
                coroutineScope {
                    launch {
                        (sources[0] as SharedFlow<Double>).collect { value ->
                            latest[0] = value
                            emit(ProcessResult3((latest[0] as? Double) ?: 0.0, (latest[1] as? Double) ?: 0.0, (latest[2] as? Double) ?: 0.0))
                        }
                    }
                    launch {
                        (sources[1] as SharedFlow<Double>).collect { value ->
                            latest[1] = value
                            emit(ProcessResult3((latest[0] as? Double) ?: 0.0, (latest[1] as? Double) ?: 0.0, (latest[2] as? Double) ?: 0.0))
                        }
                    }
                    launch {
                        (sources[2] as SharedFlow<Double>).collect { value ->
                            latest[2] = value
                            emit(ProcessResult3((latest[0] as? Double) ?: 0.0, (latest[1] as? Double) ?: 0.0, (latest[2] as? Double) ?: 0.0))
                        }
                    }
                }
            }
        )
    }
}
