/*
 * DemoUISourceCodeNode - Source node for DemoUI UI inputs
 * Generated by CodeNodeIO UIFBPInterfaceGenerator
 * License: Apache 2.0
 */

package io.codenode.testmodule.nodes

import io.codenode.testmodule.viewmodel.DemoUIState
import io.codenode.fbpdsl.model.CodeNodeFactory
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.model.CodeNodeType
import io.codenode.fbpdsl.runtime.NodeRuntime
import io.codenode.fbpdsl.runtime.PortSpec
import io.codenode.fbpdsl.runtime.ProcessResult3
import kotlinx.coroutines.flow.drop
import kotlinx.coroutines.flow.combine

object DemoUISourceCodeNode : CodeNodeDefinition {
    override val name = "DemoUISource"
    override val category = CodeNodeType.SOURCE
    override val description = "Emits UI input values into the processing graph"
    override val inputPorts = emptyList<PortSpec>()
    override val outputPorts = listOf(
        PortSpec("a", Double::class),
        PortSpec("b", Double::class),
        PortSpec("c", Double::class)
    )

    override fun createRuntime(name: String): NodeRuntime {
        return CodeNodeFactory.createSourceOut3<Double, Double, Double>(
            name = name,
            generate = { emit ->
                combine(
                DemoUIState._a,
                DemoUIState._b,
                DemoUIState._c
                ) { values -> values }
                    .drop(1)
                    .collect {
                        emit(ProcessResult3(DemoUIState._a.value, DemoUIState._b.value, DemoUIState._c.value))
                    }
            }
        )
    }
}
