/*
 * XYCoordsState
 * Generated by CodeNodeIO UIFBPStateGenerator (feature 087 / Design B)
 * License: Apache 2.0
 */

package io.codenode.xycoordrepo.viewmodel

data class XYCoordsState(
    val result: Any? = null,
    val error: Any? = null
)
