/*
 * XYCoordsViewModel
 * Generated by CodeNodeIO UIFBPViewModelGenerator (feature 087 / Design B)
 * License: Apache 2.0
 */

package io.codenode.xycoordrepo.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import io.codenode.fbpdsl.model.ExecutionState
import io.codenode.fbpdsl.model.FlowGraph
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import io.codenode.xycoordrepo.controller.XYCoordsControllerInterface

class XYCoordsViewModel(
    private val controller: XYCoordsControllerInterface
) : ViewModel() {

    private val _state = MutableStateFlow(XYCoordsState())
    val state: StateFlow<XYCoordsState> = _state.asStateFlow()

    val executionState: StateFlow<ExecutionState> = controller.executionState

    init {
        viewModelScope.launch {
            controller.result.collect { value ->
                _state.update { it.copy(result = value) }
            }
        }
        viewModelScope.launch {
            controller.error.collect { value ->
                _state.update { it.copy(error = value) }
            }
        }
    }

    fun onEvent(event: XYCoordsEvent) {
        when (event) {
            is XYCoordsEvent.UpdateSave -> controller.emitSave(event.value)
            is XYCoordsEvent.UpdateUpdate -> controller.emitUpdate(event.value)
            is XYCoordsEvent.UpdateRemove -> controller.emitRemove(event.value)
        }
    }

    fun start(): FlowGraph = controller.start()
    fun stop(): FlowGraph = controller.stop()
    fun pause(): FlowGraph = controller.pause()
    fun resume(): FlowGraph = controller.resume()
    fun reset(): FlowGraph = controller.reset()

    // ========== Type Conversion Bridging (FR-029) ==========
    // No bridging stubs needed — Screen State field types match the
    // FBP-side IP types declared in {Name}GraphNode.kt's exposeOutput calls,
    // OR `spec.screenStateFieldTypes` was not populated by the caller. Add
    // converters here manually if needed.
}
