/*
 * XYCoordsEvent
 * Generated by CodeNodeIO UIFBPEventGenerator (feature 087 / FR-002)
 * License: Apache 2.0
 */

package io.codenode.xycoordrepo.viewmodel

sealed interface XYCoordsEvent {
    data class UpdateSave(val value: Any) : XYCoordsEvent
    data class UpdateUpdate(val value: Any) : XYCoordsEvent
    data class UpdateRemove(val value: Any) : XYCoordsEvent
}
