/*
 * GraphNode Template: Group
 * @GraphNodeTemplate
 * @TemplateName Group
 * @Description Grouped from 4 nodes
 * @InputPorts 1
 * @OutputPorts 1
 * @ChildNodes 4
 * Created: 2026-06-20T18:07:36.890126
 * License: Apache 2.0
 */

package graphnodes

import io.codenode.fbpdsl.dsl.*
import io.codenode.fbpdsl.model.*
import io.codenode.fbpdsl.runtime.*

val groupGraphNode: GraphNode = graphNode("Group") {
    description = "Grouped from 4 nodes"
    position(300.0, 180.0)

    // Child nodes
    val child_conditionbranch = codeNode("ConditionBranch") {
        position(60.0, 120.0)
        input("amount", Any::class)
        output("approved", Any::class)
        output("escalated", Any::class)
        config("_genericType", "in1out2")
        config("_codeNodeDefinition", "true")
        config("_codeNodeClass", "io.codenode.expenseapproval.nodes.ConditionBranchCodeNode")
    }

    val child_approve_1 = codeNode("Approve") {
        position(300.0, 0.0)
        input("amount", Any::class)
        output("decision", Any::class)
        config("_genericType", "in1out1")
        config("_codeNodeDefinition", "true")
        config("_codeNodeClass", "io.codenode.expenseapproval.nodes.ApproveCodeNode")
    }

    val child_escalate_2 = codeNode("Escalate") {
        position(300.0, 240.0)
        input("amount", Any::class)
        output("decision", Any::class)
        config("_genericType", "in1out1")
        config("_codeNodeDefinition", "true")
        config("_codeNodeClass", "io.codenode.expenseapproval.nodes.EscalateCodeNode")
    }

    val child_mergedecision_3 = codeNode("MergeDecision", nodeType = "MERGER") {
        position(540.0, 120.0)
        input("input1", Any::class)
        input("input2", Any::class)
        output("output1", Any::class)
        config("_genericType", "in2out1")
    }

    // Internal connections
    internalConnection(child_conditionbranch, "approved", child_approve_1, "amount")
    internalConnection(child_conditionbranch, "approved", child_approve_1, "amount") withType "ip_expenseamount"
    internalConnection(child_conditionbranch, "escalated", child_escalate_2, "amount") withType "ip_expenseamount"
    internalConnection(child_approve_1, "decision", child_mergedecision_3, "input1") withType "ip_approvaldecision"
    internalConnection(child_escalate_2, "decision", child_mergedecision_3, "input2") withType "ip_approvaldecision"

    // Port mappings
    portMapping("input1", "child_conditionbranch", "amount")
    portMapping("output1", "child_mergedecision_3", "output1")

    // Exposed input ports
    exposeInput("amount", Any::class)

    // Exposed output ports
    exposeOutput("decision", Any::class)
}


/**
 * Compiled GraphNodeDefinition for Group. Generated by
 * GraphNodeTemplateSerializer alongside the canvas-managed `groupGraphNode`
 * template val above. The companion META-INF/codenode/graphnode-definitions
 * resource lists this object's FQN so NodeDefinitionRegistry surfaces it
 * at workspace load + post-Recompile.
 */
internal object GroupGraphNode : GraphNodeDefinition {
    override val name: String = "Group"
    override val category: GraphNodeCategory = GraphNodeCategory.GRAPH
    override val description: String? = "Grouped from 4 nodes"
    override val inputPorts: List<PortSpec> = listOf(PortSpec("amount", Any::class))
    override val outputPorts: List<PortSpec> = listOf(PortSpec("decision", Any::class))

    override fun createRuntime(name: String, childLookup: (String) -> NodeDefinition?): GraphNodeRuntime =
        CompiledGraphNodeRuntime(name, groupGraphNode, childLookup)
}
