/*
 * UserProfilesRuntime — Universal-runtime factory for the UserProfiles module
 * Generated by CodeNodeIO ModuleRuntimeGenerator
 * License: Apache 2.0
 */

package io.codenode.userprofiles.controller

import io.codenode.fbpdsl.model.FlowGraph
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.runtime.DynamicPipelineController
import io.codenode.fbpdsl.runtime.ModuleController
import io.codenode.userprofiles.viewmodel.UserProfilesState
import io.codenode.userprofiles.nodes.UserProfileCUDCodeNode
import io.codenode.userprofiles.nodes.UserProfileRepositoryCodeNode
import io.codenode.userprofiles.nodes.UserProfilesDisplayCodeNode

/**
 * Module-local lookup for resolving node names to compiled CodeNodeDefinitions.
 * Used by [DynamicPipelineController] when running this module without the GraphEditor.
 */
object UserProfilesNodeRegistry {
    fun lookup(name: String): CodeNodeDefinition? = when (name) {
        "UserProfileCUD" -> UserProfileCUDCodeNode
        "UserProfileRepository" -> UserProfileRepositoryCodeNode
        "UserProfilesDisplay" -> UserProfilesDisplayCodeNode
        else -> null
    }
}

/**
 * Constructs a UserProfilesControllerInterface backed by [DynamicPipelineController].
 *
 * Production-app consumers call this directly. The UserProfilesViewModel
 * constructor takes both this controller AND a `UserProfileDao` — the DAO is
 * wired at the consumer site (e.g., from `UserProfilesPersistence.dao`), not here.
 */
fun createUserProfilesRuntime(flowGraph: FlowGraph): UserProfilesControllerInterface {
    val controller = DynamicPipelineController(
        flowGraphProvider = { flowGraph },
        lookup = UserProfilesNodeRegistry::lookup,
        onReset = UserProfilesState::reset
    )
    return object : UserProfilesControllerInterface, ModuleController by controller {
        override val save = UserProfilesState.saveFlow
        override val update = UserProfilesState.updateFlow
        override val remove = UserProfilesState.removeFlow
        override val result = UserProfilesState.resultFlow
        override val error = UserProfilesState.errorFlow
    }
}
