/*
 * EALogicUserInterface — Feature 103 generated composable for EALogic UI Draft
 * Generated by CodeNodeIO UIDraftComposableGenerator
 * License: Apache 2.0
 */

package io.codenode.expenseapproval.userInterface

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.Button
import androidx.compose.material.Checkbox
import androidx.compose.material.MaterialTheme
import androidx.compose.material.OutlinedTextField
import androidx.compose.material.Surface
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import io.codenode.expenseapproval.viewmodel.EALogicEvent
import io.codenode.expenseapproval.viewmodel.EALogicState
import io.codenode.expenseapproval.viewmodel.RuntimeStatus
import io.codenode.expenseapproval.iptypes.ApprovalDecision

@Composable
internal fun EALogicUserInterface(
    state: EALogicState,
    onEvent: (EALogicEvent) -> Unit,
    modifier: Modifier = Modifier,
) {
    Column(modifier = modifier.fillMaxWidth()) {
        Surface(modifier = Modifier.fillMaxWidth().padding(8.dp)) {
            Column {
                Text("UI Inputs", style = MaterialTheme.typography.h6)
                Text("amount: Double", style = MaterialTheme.typography.subtitle1)
                OutlinedTextField(
                    value = state.formFields["ealogic_in_conditionbranch_amount"]?.values?.get("amount").orEmpty(),
                    onValueChange = { onEvent(EALogicEvent.OnFieldEdit("ealogic_in_conditionbranch_amount", "amount", it)) },
                    label = { Text("amount") },
                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                    isError = run {
                        val status = state.runtimeStatus["ealogic_in_conditionbranch_amount"]
                        status is RuntimeStatus.EmitError && status.propertyName == "amount"
                    },
                    modifier = Modifier.fillMaxWidth(),
                )
                Button(onClick = { onEvent(EALogicEvent.OnEmit("ealogic_in_conditionbranch_amount")) }) { Text("Emit") }
                when (val status = state.runtimeStatus["ealogic_in_conditionbranch_amount"]) {
                    RuntimeStatus.RuntimeNotActive -> Text("runtime not active", color = MaterialTheme.colors.error)
                    is RuntimeStatus.EmitError -> Text(status.message, color = MaterialTheme.colors.error)
                    else -> Unit
                }
            }
        }
        Surface(modifier = Modifier.fillMaxWidth().padding(8.dp)) {
            Column {
                Text("Displayed Outputs", style = MaterialTheme.typography.h6)
                Text("output1: Double", style = MaterialTheme.typography.subtitle1)
                run {
                    val ip = state.latestIps["ealogic_out_mergedecision_output1"]?.ip
                    run {
                        val value = (ip as? ApprovalDecision)?.amount?.toString()
                        Text("amount: " + (value ?: "(awaiting first IP)"))
                    }
                    Text("unsupported: status", style = MaterialTheme.typography.body2, color = MaterialTheme.colors.onSurface.copy(alpha = 0.6f))
                    run {
                        val value = (ip as? ApprovalDecision)?.approverName?.toString()
                        Text("approverName: " + (value ?: "(awaiting first IP)"))
                    }
                    run {
                        val value = (ip as? ApprovalDecision)?.approverRole?.toString()
                        Text("approverRole: " + (value ?: "(awaiting first IP)"))
                    }
                }
            }
        }
    }
}
