/*
 * GeoLocations Composable
 * Generated by CodeNodeIO EntityUIGenerator
 * License: Apache 2.0
 */

package io.codenode.geolocations.userInterface

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import io.codenode.geolocations.GeoLocationsViewModel
import io.codenode.persistence.GeoLocationEntity

@Composable
fun GeoLocations(
    viewModel: GeoLocationsViewModel,
    modifier: Modifier = Modifier
) {
    val geoLocations by viewModel.geoLocations.collectAsState()
    var selectedId by remember { mutableStateOf<Long?>(null) }
    var showAddForm by remember { mutableStateOf(false) }
    var showUpdateForm by remember { mutableStateOf(false) }
    var showRemoveConfirmation by remember { mutableStateOf(false) }

    val selectedItem = geoLocations.find { it.id == selectedId }

    // Clear selection if the selected item was removed externally
    LaunchedEffect(geoLocations, selectedId) {
        if (selectedId != null && selectedItem == null) {
            selectedId = null
        }
    }

    if (showAddForm) {
        AddUpdateGeoLocation(
            existingItem = null,
            onSave = { item ->
                viewModel.addEntity(item)
                showAddForm = false
            },
            onCancel = { showAddForm = false },
            modifier = modifier
        )
        return
    }

    if (showUpdateForm && selectedItem != null) {
        AddUpdateGeoLocation(
            existingItem = selectedItem,
            onSave = { item ->
                viewModel.updateEntity(item)
                showUpdateForm = false
                selectedId = null
            },
            onCancel = { showUpdateForm = false },
            modifier = modifier
        )
        return
    }

    Column(
        modifier = modifier.fillMaxSize().padding(16.dp)
    ) {
        Text(
            text = "GeoLocations",
            style = MaterialTheme.typography.headlineMedium,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        // List or empty state
        Box(modifier = Modifier.weight(1f)) {
            if (geoLocations.isEmpty()) {
                Text(
                    text = "No geoLocations yet",
                    style = MaterialTheme.typography.bodyLarge,
                    modifier = Modifier.align(Alignment.Center)
                )
            } else {
                LazyColumn(modifier = Modifier.fillMaxSize()) {
                    items(geoLocations, key = { it.id }) { item ->
                        GeoLocationRow(
                            item = item,
                            isSelected = item.id == selectedId,
                            onClick = {
                                selectedId = if (selectedId == item.id) null else item.id
                            }
                        )
                    }
                }
            }
        }

        // Button row
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(top = 16.dp),
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            Button(onClick = { showAddForm = true }) {
                Text("Add")
            }
            Button(
                onClick = { showUpdateForm = true },
                enabled = selectedItem != null
            ) {
                Text("Update")
            }
            Button(
                onClick = { showRemoveConfirmation = true },
                enabled = selectedItem != null
            ) {
                Text("Remove")
            }
        }

        if (showRemoveConfirmation && selectedItem != null) {
            AlertDialog(
                onDismissRequest = { showRemoveConfirmation = false },
                title = { Text("Remove this item?") },
                text = { Text("Are you sure you want to remove this geoLocation?") },
                confirmButton = {
                    TextButton(onClick = {
                        viewModel.removeEntity(selectedItem)
                        selectedId = null
                        showRemoveConfirmation = false
                    }) {
                        Text("Confirm")
                    }
                },
                dismissButton = {
                    TextButton(onClick = { showRemoveConfirmation = false }) {
                        Text("Cancel")
                    }
                }
            )
        }
    }
}
