/*
 * Build script for WeatherForecast
 * Module: WeatherForecast
 * Version: 1.0.0
 * Generated by CodeNodeIO ModuleGenerator
 * License: Apache 2.0
 */

plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization")
    id("org.jetbrains.compose")
    id("org.jetbrains.kotlin.plugin.compose")
    id("com.android.library")
}

kotlin {
    jvm {
        compilations.all {
            kotlinOptions.jvmTarget = "17"
        }
    }

    androidTarget {
        compilations.all {
            kotlinOptions.jvmTarget = "17"
        }
    }

    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "WeatherForecast"
            isStatic = true
        }
    }

    // Use default hierarchy template for shared iOS source sets
    applyDefaultHierarchyTemplate()

    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation(project(":fbpDsl"))
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0")
                // Ktor Client (KMP) for HTTPS requests
                implementation("io.ktor:ktor-client-core:3.1.1")
                implementation("io.ktor:ktor-client-content-negotiation:3.1.1")
                implementation("io.ktor:ktor-serialization-kotlinx-json:3.1.1")
                // KMP-compatible lifecycle support (works on all platforms)
                implementation("org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose:2.8.0")
                // Compose UI dependencies (for userInterface composables)
                // Use explicit 1.7.3 to match KMPMobileApp and stay compatible with compileSdk 34
                implementation("org.jetbrains.compose.runtime:runtime:1.7.3")
                implementation("org.jetbrains.compose.foundation:foundation:1.7.3")
                implementation("org.jetbrains.compose.material3:material3:1.7.3")
                implementation("org.jetbrains.compose.ui:ui:1.7.3")
                // JetBrains Multiplatform ViewModel
                implementation("org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose:2.8.0")
            }
        }

        val commonTest by getting {
            dependencies {
                implementation(kotlin("test"))
            }
        }

        val jvmMain by getting {
            dependencies {
                // Ktor CIO engine for JVM/Desktop
                implementation("io.ktor:ktor-client-cio:3.1.1")
            }
        }

        val androidMain by getting {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.0")
                // Ktor CIO engine for Android
                implementation("io.ktor:ktor-client-cio:3.1.1")
            }
        }

        val iosMain by getting {
            dependencies {
                // Ktor Darwin engine for iOS
                implementation("io.ktor:ktor-client-darwin:3.1.1")
            }
        }
    }
}

android {
    namespace = "io.codenode.generated.WeatherForecast"
    compileSdk = 34

    defaultConfig {
        minSdk = 24
        targetSdk = 34
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}
