/*
 * XYCoordsPreviewProvider — Registers XYCoords preview composables for the runtime panel
 * Generated by CodeNodeIO PreviewProviderGenerator
 * License: Apache 2.0
 */

package io.codenode.xycoordrepo.userInterface

import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import io.codenode.xycoordrepo.viewmodel.XYCoordsViewModel
import io.codenode.previewapi.PreviewRegistry

/**
 * Provides preview composables that render XYCoords components,
 * driven by the RuntimeSession's ViewModel state.
 *
 * Per feature 087 / Design B, the registered lambda is the host-app
 * "ScreenRoot" seam: it collects `viewModel.state` as Compose state and
 * passes `viewModel::onEvent` to the pure two-parameter XYCoords Screen.
 */
object XYCoordsPreviewProvider {

    /**
     * Registers XYCoords preview composables with the PreviewRegistry.
     */
    fun register() {
        PreviewRegistry.register("XYCoords") { viewModel, modifier ->
            val vm = viewModel as XYCoordsViewModel
            val state by vm.state.collectAsState()
            XYCoords(state = state, onEvent = vm::onEvent, modifier = modifier)
        }
    }
}
