/*
 * EALogicSinkCodeNode — Sink node for EALogic UI display.
 * Generated by CodeNodeIO UIFBPSinkCodeNodeGenerator (feature 087 / Decision 8)
 * License: Apache 2.0
 */

package io.codenode.expenseapproval.nodes

import io.codenode.fbpdsl.model.CodeNodeFactory
import io.codenode.fbpdsl.model.CodeNodeType
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.runtime.NodeRuntime
import io.codenode.fbpdsl.runtime.PortSpec

object EALogicSinkCodeNode : CodeNodeDefinition {
    override val name = "EALogicSink"
    override val category = CodeNodeType.SINK
    override val description = "Receives processed results for EALogic UI display"
    override val inputPorts = listOf(
        PortSpec("amount", Any::class),
        PortSpec("status", ExpenseApprovalStatus::class),
        PortSpec("approver", Approver::class)
    )
    override val outputPorts = emptyList<PortSpec>()

    /** Default runtime: no-op reporters. Safe for palette drops outside a UI-FBP runtime. */
    override fun createRuntime(name: String): NodeRuntime =
        buildRuntime(name, Array(3) { { _: Any? -> } })

    /**
     * Returns a per-flow-graph CodeNodeDefinition wrapper that delivers received
     * IPs to [reporters]. The Runtime factory passes one reporter per sinkInput,
     * in declared order. Decision 8 / Design B.
     */
    fun withReporters(vararg reporters: (Any?) -> Unit): CodeNodeDefinition =
        object : CodeNodeDefinition by this {
            override fun createRuntime(name: String): NodeRuntime =
                buildRuntime(name, reporters)
        }

    private fun buildRuntime(name: String, reporters: Array<out (Any?) -> Unit>): NodeRuntime {
        return CodeNodeFactory.createSinkIn3Any<Any, ExpenseApprovalStatus, Approver>(
            name = name,
            initialValue1 = "",
            initialValue2 = Any(),
            initialValue3 = Any(),
            consume = { amount, status, approver ->
                reporters[0](amount)
                reporters[1](status)
                reporters[2](approver)
            }
        )
    }
}
