/*
 * ExpenseApprovalLogicSourceCodeNode — Feature 103 US1d generated AGGREGATED Source CodeNode
 * Generated by CodeNodeIO UIDraftSourceCodeNodeGenerator
 * Aggregates 1 input port(s): 'in_conditionbranch_amount'
 * License: Apache 2.0
 */

package io.codenode.expenseapproval.nodes

import io.codenode.expenseapproval.iptypes.ExpenseAmount
import io.codenode.fbpdsl.model.CodeNodeFactory.createContinuousSource
import io.codenode.fbpdsl.model.CodeNodeType
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.runtime.NodeRuntime
import io.codenode.fbpdsl.runtime.PortSpec
import kotlinx.coroutines.channels.Channel

/**
 * Aggregated Source CodeNode covering all of the GraphNode's input ports.
 * The ViewModel pushes assembled IPs into the per-port channel via
 * `emitChannels.getValue("<portName>").trySend(ip)`.
 */
internal object ExpenseApprovalLogicSourceCodeNode : CodeNodeDefinition {
    override val name: String = "ExpenseApprovalLogicSource"
    override val category: CodeNodeType = CodeNodeType.SOURCE
    override val inputPorts: List<PortSpec> = emptyList()
    override val outputPorts: List<PortSpec> = listOf(
        PortSpec("in_conditionbranch_amount", ExpenseAmount::class),
    )

    /** ViewModel pushes assembled IPs into the per-port channel keyed by port name. */
    val emitChannels: Map<String, Channel<Any>> = mapOf(
        "in_conditionbranch_amount" to Channel(Channel.BUFFERED),
    )

    override fun createRuntime(name: String): NodeRuntime =
        createContinuousSource<Any>(name) { emit ->
            for (ip in emitChannels.getValue("in_conditionbranch_amount")) emit(ip)
        }
}
