/*
 * ExpenseApprovalLogicSinkCodeNode — Feature 103 US1d generated AGGREGATED Sink CodeNode
 * Generated by CodeNodeIO UIDraftSinkCodeNodeGenerator
 * Aggregates 1 output port(s): 'out_mergedecision_output1'
 * License: Apache 2.0
 */

package io.codenode.expenseapproval.nodes

import io.codenode.expenseapproval.iptypes.ApprovalDecision
import io.codenode.fbpdsl.model.CodeNodeFactory.createContinuousSink
import io.codenode.fbpdsl.model.CodeNodeType
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.runtime.NodeRuntime
import io.codenode.fbpdsl.runtime.PortSpec
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/**
 * Aggregated Sink CodeNode covering all of the GraphNode's output ports.
 * The ViewModel subscribes per-port via `latestIps.getValue("<portName>").collect { … }`
 * inside `viewModelScope.launch { … }` from `init`.
 */
internal object ExpenseApprovalLogicSinkCodeNode : CodeNodeDefinition {
    override val name: String = "ExpenseApprovalLogicSink"
    override val category: CodeNodeType = CodeNodeType.SINK
    override val inputPorts: List<PortSpec> = listOf(
        PortSpec("out_mergedecision_output1", ApprovalDecision::class),
    )
    override val outputPorts: List<PortSpec> = emptyList()

    private val _latestIp_out_mergedecision_output1: MutableStateFlow<Any?> = MutableStateFlow(null)

    /** Per-port latest-IP read-only StateFlows; the ViewModel collects from these. */
    val latestIps: Map<String, StateFlow<Any?>> = mapOf(
        "out_mergedecision_output1" to _latestIp_out_mergedecision_output1.asStateFlow(),
    )

    override fun createRuntime(name: String): NodeRuntime =
        createContinuousSink<Any>(name) { ip ->
            _latestIp_out_mergedecision_output1.value = ip
        }
}
