/*
 * GeoLocationsViewModel
 * Generated by CodeNodeIO RuntimeViewModelGenerator
 * License: Apache 2.0
 */

package io.codenode.geolocations

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import io.codenode.fbpdsl.model.ExecutionState
import io.codenode.fbpdsl.model.FlowGraph
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import io.codenode.geolocations.generated.GeoLocationsControllerInterface
import io.codenode.geolocations.iptypes.GeoLocation
import io.codenode.geolocations.iptypes.toGeoLocation
import io.codenode.persistence.GeoLocationDao
import io.codenode.persistence.GeoLocationRepository

// ===== MODULE PROPERTIES START =====
// Auto-generated from source output ports and sink input ports. Do not edit this section manually.
// Changes here will be overwritten on next code generation.

object GeoLocationsState {

    internal val _save = MutableStateFlow<GeoLocation?>(null)
    val saveFlow: StateFlow<GeoLocation?> = _save.asStateFlow()

    internal val _update = MutableStateFlow<GeoLocation?>(null)
    val updateFlow: StateFlow<GeoLocation?> = _update.asStateFlow()

    internal val _remove = MutableStateFlow<GeoLocation?>(null)
    val removeFlow: StateFlow<GeoLocation?> = _remove.asStateFlow()

    internal val _result = MutableStateFlow<String?>(null)
    val resultFlow: StateFlow<String?> = _result.asStateFlow()

    internal val _error = MutableStateFlow<String?>(null)
    val errorFlow: StateFlow<String?> = _error.asStateFlow()

    internal val _geoLocations = MutableStateFlow<List<GeoLocation>>(emptyList())

    fun reset() {
        _save.value = null
        _update.value = null
        _remove.value = null
        _result.value = null
        _error.value = null
        _geoLocations.value = emptyList()
    }
}

// ===== MODULE PROPERTIES END =====

// ============================================================
// ViewModel
// Binding interface between composable UI and FlowGraph.
// User-editable section below — preserved across regenerations.
// ============================================================

/**
 * ViewModel for the GeoLocations composable.
 * Bridges FlowGraph domain logic with Compose UI.
 *
 * @param controller The GeoLocationsControllerInterface that manages FlowGraph execution
 * @generated by CodeNodeIO RuntimeViewModelGenerator
 */
class GeoLocationsViewModel(
    private val controller: GeoLocationsControllerInterface,
    geoLocationDao: GeoLocationDao
) : ViewModel() {

    // Observable state from module properties
    val save: StateFlow<GeoLocation?> = GeoLocationsState.saveFlow
    val update: StateFlow<GeoLocation?> = GeoLocationsState.updateFlow
    val remove: StateFlow<GeoLocation?> = GeoLocationsState.removeFlow
    val result: StateFlow<String?> = GeoLocationsState.resultFlow
    val error: StateFlow<String?> = GeoLocationsState.errorFlow

    // Reactive entity list from repository
    val geoLocations: StateFlow<List<GeoLocation>> = GeoLocationsState._geoLocations

    // Execution state from controller
    val executionState: StateFlow<ExecutionState> = controller.executionState

    init {
        // Collect repository changes into the geoLocations StateFlow
        viewModelScope.launch {
            val repo = GeoLocationRepository(geoLocationDao)
            repo.observeAll().collect { list ->
                GeoLocationsState._geoLocations.value = list.map { it.toGeoLocation() }
            }
        }
    }

    // CRUD methods — trigger operations via the FlowGraph reactive source
    fun addEntity(geoLocation: GeoLocation) {
        GeoLocationsState._save.value = geoLocation
    }

    fun updateEntity(geoLocation: GeoLocation) {
        GeoLocationsState._update.value = geoLocation
    }

    fun removeEntity(geoLocation: GeoLocation) {
        GeoLocationsState._remove.value = geoLocation
    }

    // Control methods
    fun start(): FlowGraph = controller.start()

    fun stop(): FlowGraph = controller.stop()

    fun reset(): FlowGraph = controller.reset()

    fun pause(): FlowGraph = controller.pause()

    fun resume(): FlowGraph = controller.resume()
}

