/*
 * GeoLocationsDisplay Sink Node
 * Generated by CodeNodeIO EntityDisplayGenerator
 * License: Apache 2.0
 */

package io.codenode.geolocations

import io.codenode.fbpdsl.model.CodeNodeFactory

/**
 * Creates the GeoLocationsDisplay sink node.
 *
 * This sink node receives result and error values from the GeoLocationRepository
 * processor and updates the corresponding StateFlows in GeoLocationsState.
 */
internal fun createGeoLocationsDisplay() = CodeNodeFactory.createSinkIn2<Any, Any>(
    name = "GeoLocationsDisplay",
    consume = { result, error ->
        GeoLocationsState._result.value = result
        GeoLocationsState._error.value = error
    }
)
