/*
 * GeoLocationCUD Source Node
 * Generated by CodeNodeIO EntityCUDGenerator
 * License: Apache 2.0
 */

package io.codenode.geolocations

import io.codenode.fbpdsl.model.CodeNodeFactory
import io.codenode.fbpdsl.runtime.ProcessResult3
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.flow.drop
import kotlinx.coroutines.launch

/**
 * Creates the GeoLocationCUD source node.
 *
 * This source node collects from the save, update, and remove StateFlows
 * in GeoLocationsState and emits them as a ProcessResult3 to downstream processors.
 */
internal fun createGeoLocationCUD() = CodeNodeFactory.createSourceOut3<Any, Any, Any>(
    name = "GeoLocationCUD",
    generate = { emit ->
        coroutineScope {
            launch {
                GeoLocationsState._save.drop(1).collect { save ->
                    if (save != null) {
                        emit(ProcessResult3(save, null, null))
                        GeoLocationsState._save.value = null
                    }
                }
            }
            launch {
                GeoLocationsState._update.drop(1).collect { update ->
                    if (update != null) {
                        emit(ProcessResult3(null, update, null))
                        GeoLocationsState._update.value = null
                    }
                }
            }
            launch {
                GeoLocationsState._remove.drop(1).collect { remove ->
                    if (remove != null) {
                        emit(ProcessResult3(null, null, remove))
                        GeoLocationsState._remove.value = null
                    }
                }
            }
        }
    }
)
