/*
 * DemoUISinkCodeNode - Sink node for DemoUI UI display
 * Generated by CodeNodeIO UIFBPInterfaceGenerator
 * License: Apache 2.0
 */

package io.codenode.demo.nodes

import io.codenode.demo.DemoUIState
import io.codenode.fbpdsl.model.CodeNodeFactory
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.model.CodeNodeType
import io.codenode.fbpdsl.runtime.NodeRuntime
import io.codenode.fbpdsl.runtime.PortSpec
import io.codenode.demo.iptypes.CalculationResults

object DemoUISinkCodeNode : CodeNodeDefinition {
    override val name = "DemoUISink"
    override val category = CodeNodeType.SINK
    override val description = "Receives processed results for DemoUI UI display"
    override val inputPorts = listOf(
        PortSpec("results", CalculationResults::class)
    )
    override val outputPorts = emptyList<PortSpec>()

    override fun createRuntime(name: String): NodeRuntime {
        return CodeNodeFactory.createContinuousSink<CalculationResults>(
            name = name,
            consume = { value ->
                DemoUIState._results.value = value
            }
        )
    }
}
