/*
 * WeatherForecastRuntime — Universal-runtime factory for the WeatherForecast module
 * Generated by CodeNodeIO ModuleRuntimeGenerator
 * License: Apache 2.0
 */

package io.codenode.weatherforecast

import io.codenode.fbpdsl.model.FlowGraph
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.runtime.DynamicPipelineController
import io.codenode.fbpdsl.runtime.ModuleController
import io.codenode.weatherforecast.controller.WeatherForecastControllerInterface
import io.codenode.weatherforecast.nodes.DataMapperCodeNode
import io.codenode.weatherforecast.nodes.ForecastDisplayCodeNode
import io.codenode.weatherforecast.nodes.HttpFetcherCodeNode
import io.codenode.weatherforecast.nodes.JsonParserCodeNode
import io.codenode.weatherforecast.nodes.TriggerSourceCodeNode

/**
 * Module-local lookup for resolving node names to compiled CodeNodeDefinitions.
 * Used by [DynamicPipelineController] when running this module without the GraphEditor.
 */
object WeatherForecastNodeRegistry {
    fun lookup(name: String): CodeNodeDefinition? = when (name) {
        "DataMapper" -> DataMapperCodeNode
        "ForecastDisplay" -> ForecastDisplayCodeNode
        "HttpFetcher" -> HttpFetcherCodeNode
        "JsonParser" -> JsonParserCodeNode
        "TriggerSource" -> TriggerSourceCodeNode
        else -> null
    }
}

/**
 * Constructs a WeatherForecastControllerInterface backed by [DynamicPipelineController].
 * Closes the production-deployability gap that WeatherForecast had before feature 085 —
 * the module is now consumable by a built app without the GraphEditor in the loop.
 */
fun createWeatherForecastRuntime(flowGraph: FlowGraph): WeatherForecastControllerInterface {
    val controller = DynamicPipelineController(
        flowGraphProvider = { flowGraph },
        lookup = WeatherForecastNodeRegistry::lookup,
        onReset = WeatherForecastState::reset
    )
    return object : WeatherForecastControllerInterface, ModuleController by controller {}
}
