/*
 * GreeterRuntime — per-flow-graph factory for the Greeter UI-FBP module.
 * Generated by CodeNodeIO UIFBPInterfaceGenerator (feature 087 / Design B)
 * License: Apache 2.0
 */

package io.codenode.greeter.controller

import io.codenode.fbpdsl.model.FlowGraph
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.runtime.DynamicPipelineController
import io.codenode.fbpdsl.runtime.ModuleController
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import io.codenode.greeter.nodes.GreeterSourceCodeNode
import io.codenode.greeter.nodes.GreeterSinkCodeNode

/**
 * Constructs a GreeterControllerInterface backed by [DynamicPipelineController].
 * Per-flow-graph state lives in this function's closure — multiple
 * concurrent calls produce fully isolated controllers.
 *
 * @param fallbackLookup Resolves CodeNodeDefinitions for nodes other than
 *        the generated GreeterSourceCodeNode / GreeterSinkCodeNode wrappers (e.g., transformers,
 *        intermediate processors). The Runtime Preview path passes the
 *        NodeDefinitionRegistry-backed lookup here so any CodeNode added
 *        to the canvas resolves. Defaults to no-fallback for direct callers.
 */
fun createGreeterRuntime(
    flowGraph: FlowGraph,
    fallbackLookup: (String) -> CodeNodeDefinition? = { null }
): GreeterControllerInterface {
    val _greeting = MutableStateFlow<String>("")
    val _nameLength = MutableStateFlow<Int>(0)
    val _name = MutableSharedFlow<String>(replay = 1, extraBufferCapacity = 64)

    val sinkWrapper = GreeterSinkCodeNode.withReporters(
        { value -> _greeting.value = value as String },
        { value -> _nameLength.value = value as Int }
    )
    val sourceWrapper = GreeterSourceCodeNode.withSources(_name)

    val controller = DynamicPipelineController(
        flowGraphProvider = { flowGraph },
        lookup = { nodeName -> when (nodeName) {
            "GreeterSource" -> sourceWrapper
            "GreeterSink" -> sinkWrapper
            else -> fallbackLookup(nodeName)
        } },
        onReset = {
            _greeting.value = ""
            _nameLength.value = 0
        }
    )

    return object : GreeterControllerInterface, ModuleController by controller {
        override val greeting: StateFlow<String> = _greeting.asStateFlow()
        override val nameLength: StateFlow<Int> = _nameLength.asStateFlow()
        override fun emitName(value: String) {
            controller.coroutineScope?.launch { _name.emit(value) }
        }
    }
}
