/*
 * AddressesControllerInterface
 * Generated by CodeNodeIO RuntimeControllerInterfaceGenerator
 * License: Apache 2.0
 */

package io.codenode.addresses.controller

import io.codenode.fbpdsl.model.FlowGraph
import io.codenode.fbpdsl.runtime.ModuleController
import kotlinx.coroutines.flow.StateFlow

/**
 * Interface defining the contract for Addresses controllers.
 *
 * Extends [ModuleController] (feature 085 — universal-runtime collapse) so
 * consumers reach setAttenuationDelay/observers/getStatus through this typed
 * surface without casting to a concrete controller class.
 *
 * @generated by CodeNodeIO RuntimeControllerInterfaceGenerator
 */
interface AddressesControllerInterface : ModuleController {
    val save: StateFlow<Any?>
    val update: StateFlow<Any?>
    val remove: StateFlow<Any?>
    val result: StateFlow<Any?>
    val error: StateFlow<Any?>
}
