/*
 * AddressesControllerInterface
 * Generated by CodeNodeIO RuntimeControllerInterfaceGenerator
 * License: Apache 2.0
 */

package io.codenode.addresses.controller

import io.codenode.fbpdsl.model.ExecutionState
import io.codenode.fbpdsl.model.FlowGraph
import kotlinx.coroutines.flow.StateFlow

/**
 * Interface defining the contract for Addresses controllers.
 *
 * Enables dependency injection and testing by allowing
 * both the real AddressesController and test fakes to be used.
 *
 * @generated by CodeNodeIO RuntimeControllerInterfaceGenerator
 */
interface AddressesControllerInterface {

    val save: StateFlow<Any?>
    val update: StateFlow<Any?>
    val remove: StateFlow<Any?>
    val result: StateFlow<Any?>
    val error: StateFlow<Any?>

    val executionState: StateFlow<ExecutionState>

    fun start(): FlowGraph

    fun stop(): FlowGraph

    fun reset(): FlowGraph

    fun pause(): FlowGraph

    fun resume(): FlowGraph
}

