/*
 * AddressesControllerAdapter
 * Generated by CodeNodeIO RuntimeControllerAdapterGenerator
 * License: Apache 2.0
 */

package io.codenode.addresses.controller

import io.codenode.fbpdsl.model.ExecutionState
import io.codenode.fbpdsl.model.FlowGraph
import kotlinx.coroutines.flow.StateFlow

/**
 * Adapter that wraps the generated AddressesController to implement
 * AddressesControllerInterface.
 *
 * @param controller The generated AddressesController to wrap
 * @generated by CodeNodeIO RuntimeControllerAdapterGenerator
 */
class AddressesControllerAdapter(
    private val controller: AddressesController
) : AddressesControllerInterface {

    override val save: StateFlow<Any?>
        get() = controller.save

    override val update: StateFlow<Any?>
        get() = controller.update

    override val remove: StateFlow<Any?>
        get() = controller.remove

    override val result: StateFlow<Any?>
        get() = controller.result

    override val error: StateFlow<Any?>
        get() = controller.error

    override val executionState: StateFlow<ExecutionState>
        get() = controller.executionState

    override fun start(): FlowGraph = controller.start()

    override fun stop(): FlowGraph = controller.stop()

    override fun reset(): FlowGraph = controller.reset()

    override fun pause(): FlowGraph = controller.pause()

    override fun resume(): FlowGraph = controller.resume()
}

