/*
 * Addresses Controller
 * Generated by CodeNodeIO RuntimeControllerGenerator
 * License: Apache 2.0
 */

package io.codenode.addresses.controller
import io.codenode.addresses.flow.AddressesFlow

import io.codenode.addresses.viewmodel.AddressesState

import io.codenode.fbpdsl.model.RootControlNode
import io.codenode.fbpdsl.model.FlowGraph
import io.codenode.fbpdsl.model.FlowExecutionStatus
import io.codenode.fbpdsl.model.ExecutionState
import io.codenode.fbpdsl.model.ControlConfig
import io.codenode.fbpdsl.runtime.ModuleController
import io.codenode.fbpdsl.runtime.RuntimeRegistry
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.LifecycleEventObserver
import androidx.lifecycle.LifecycleOwner
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

/**
 * Controller for Addresses flow execution.
 *
 * Provides unified control operations for starting, pausing,
 * stopping, and monitoring the flow execution.
 *
 * @param flowGraph The FlowGraph instance to control
 * @generated by CodeNodeIO RuntimeControllerGenerator
 */
class AddressesController(
    private var flowGraph: FlowGraph
) : ModuleController {

    private val registry = RuntimeRegistry()

    private var controller: RootControlNode = RootControlNode.createFor(
        flowGraph = flowGraph,
        name = "AddressesController",
        registry = registry
    )

    private val flow = AddressesFlow()

    private var flowScope: CoroutineScope? = null

    private var wasRunningBeforePause: Boolean = false

    private var emissionObserver: ((String, Int) -> Unit)? = null
    private var valueObserver: ((String, Int, Any?) -> Unit)? = null

    val save: StateFlow<Any?> = flow.saveFlow
    val update: StateFlow<Any?> = flow.updateFlow
    val remove: StateFlow<Any?> = flow.removeFlow
    val result: StateFlow<Any?> = flow.resultFlow
    val error: StateFlow<Any?> = flow.errorFlow

    private val _executionState = MutableStateFlow(ExecutionState.IDLE)
    override val executionState: StateFlow<ExecutionState> = _executionState.asStateFlow()

    override fun start(): FlowGraph {
        flowGraph = controller.startAll()
        controller = RootControlNode.createFor(flowGraph, "AddressesController", registry)
        _executionState.value = ExecutionState.RUNNING

        flowScope?.cancel()
        val scope = CoroutineScope(SupervisorJob() + Dispatchers.Default)
        flowScope = scope

        flow.addressRepository.registry = registry
        flow.addressCUD.registry = registry
        flow.addressesDisplay.registry = registry

        flow.addressCUD.executionState = ExecutionState.RUNNING
        scope.launch {
            flow.start(scope)
        }

        return flowGraph
    }

    override fun pause(): FlowGraph {
        flowGraph = controller.pauseAll()
        controller = RootControlNode.createFor(flowGraph, "AddressesController", registry)
        _executionState.value = ExecutionState.PAUSED
        return flowGraph
    }

    override fun resume(): FlowGraph {
        flowGraph = controller.resumeAll()
        controller = RootControlNode.createFor(flowGraph, "AddressesController", registry)
        _executionState.value = ExecutionState.RUNNING
        return flowGraph
    }

    override fun stop(): FlowGraph {
        flowGraph = controller.stopAll()
        controller = RootControlNode.createFor(flowGraph, "AddressesController", registry)
        _executionState.value = ExecutionState.IDLE

        flow.stop()
        flowScope?.cancel()
        flowScope = null

        return flowGraph
    }

    override fun reset(): FlowGraph {
        wasRunningBeforePause = false
        stop()
        flow.reset()
        return flowGraph
    }

    fun getStatus(): FlowExecutionStatus {
        return controller.getStatus()
    }

    fun setNodeState(nodeId: String, state: ExecutionState): FlowGraph {
        flowGraph = controller.setNodeState(nodeId, state)
        controller = RootControlNode.createFor(flowGraph, "AddressesController")
        return flowGraph
    }

    fun setNodeConfig(nodeId: String, config: ControlConfig): FlowGraph {
        flowGraph = controller.setNodeConfig(nodeId, config)
        controller = RootControlNode.createFor(flowGraph, "AddressesController")
        return flowGraph
    }

    fun bindToLifecycle(lifecycle: Lifecycle) {
        lifecycle.addObserver(object : LifecycleEventObserver {
            override fun onStateChanged(source: LifecycleOwner, event: Lifecycle.Event) {
                when (event) {
                    Lifecycle.Event.ON_START -> {
                        if (wasRunningBeforePause) {
                            start()
                            wasRunningBeforePause = false
                        }
                    }
                    Lifecycle.Event.ON_STOP -> {
                        val status = getStatus()
                        wasRunningBeforePause = status.overallState == ExecutionState.RUNNING
                        if (wasRunningBeforePause) {
                            pause()
                        }
                    }
                    Lifecycle.Event.ON_DESTROY -> {
                        stop()
                    }
                    else -> { /* no-op */ }
                }
            }
        })
    }

    /**
     * Sets the attenuation delay on all runtime nodes.
     * When non-null and > 0, processors delay between receive and process.
     * When null or 0, processors process immediately (default behavior).
     */
    override fun setAttenuationDelay(ms: Long?) {
        flow.addressRepository.attenuationDelayMs = ms
        flow.addressCUD.attenuationDelayMs = ms
        flow.addressesDisplay.attenuationDelayMs = ms
    }

    override fun setEmissionObserver(observer: ((String, Int) -> Unit)?) {
        emissionObserver = observer
        applyEmissionObserver()
    }

    private fun applyEmissionObserver() {
        val obs = emissionObserver
        flow.addressRepository.onEmit = obs
        flow.addressCUD.onEmit = obs
        flow.addressesDisplay.onEmit = obs
    }

    override fun setValueObserver(observer: ((String, Int, Any?) -> Unit)?) {
        valueObserver = observer
        applyValueObserver()
    }

    private fun applyValueObserver() {
        val obs = valueObserver
        flow.addressRepository.onEmitValue = obs
        flow.addressCUD.onEmitValue = obs
        flow.addressesDisplay.onEmitValue = obs
    }

    val currentFlowGraph: FlowGraph
        get() = flowGraph
}

