/*
 * WeatherForecastControllerInterface
 * Generated by CodeNodeIO RuntimeControllerInterfaceGenerator
 * License: Apache 2.0
 */

package io.codenode.weatherforecast.controller

import io.codenode.fbpdsl.runtime.FlowGraphController

/**
 * Interface defining the contract for WeatherForecast controllers.
 *
 * Extends [FlowGraphController] (feature 085 — universal-runtime collapse) so
 * consumers reach setAttenuationDelay/observers/getStatus through this typed
 * surface without casting to a concrete controller class.
 *
 * @generated by CodeNodeIO RuntimeControllerInterfaceGenerator
 */
interface WeatherForecastControllerInterface : FlowGraphController
