/*
 * UserProfiles Composable
 * Generated by CodeNodeIO
 * License: Apache 2.0
 */

package io.codenode.userprofiles.userInterface

import androidx.compose.foundation.layout.*
import androidx.compose.material3.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import io.codenode.userprofiles.generated.UserProfilesViewModel

@Composable
fun UserProfiles(
    viewModel: UserProfilesViewModel,
    modifier: Modifier = Modifier
) {
    // TODO: Implement UserProfiles UI
    Column(
        modifier = modifier,
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Text("UserProfiles")
    }
}
