/*
 * DemoUIState
 * Generated by CodeNodeIO UIFBPInterfaceGenerator
 * License: Apache 2.0
 */

package io.codenode.demo

import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import io.codenode.demo.iptypes.CalculationResults

object DemoUIState {

    internal val _a = MutableStateFlow<Double>(0.0)
    val aFlow: StateFlow<Double> = _a.asStateFlow()

    internal val _b = MutableStateFlow<Double>(0.0)
    val bFlow: StateFlow<Double> = _b.asStateFlow()

    internal val _results = MutableStateFlow<CalculationResults?>(null)
    val resultsFlow: StateFlow<CalculationResults?> = _results.asStateFlow()

    fun reset() {
        _a.value = 0.0
        _b.value = 0.0
        _results.value = null
    }
}
