/*
 * DemoUIViewModel
 * Generated by CodeNodeIO UIFBPInterfaceGenerator
 * License: Apache 2.0
 */

package io.codenode.demo

import androidx.lifecycle.ViewModel
import kotlinx.coroutines.flow.StateFlow
import io.codenode.demo.iptypes.CalculationResults

class DemoUIViewModel : ViewModel() {

    val results: StateFlow<CalculationResults?> = DemoUIState.resultsFlow

    fun emit(a: Double, b: Double) {
        DemoUIState._a.value = a
        DemoUIState._b.value = b
    }

    fun reset() {
        DemoUIState.reset()
    }
}
