/*
 * EALogicRuntime — per-flow-graph factory for the EALogic UI-FBP module.
 * Generated by CodeNodeIO UIFBPInterfaceGenerator (feature 087 / Design B)
 * License: Apache 2.0
 */

package io.codenode.expenseapproval.controller

import io.codenode.fbpdsl.model.FlowGraph
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.runtime.DynamicPipelineController
import io.codenode.fbpdsl.runtime.ModuleController
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import io.codenode.expenseapproval.nodes.EALogicSourceCodeNode
import io.codenode.expenseapproval.nodes.EALogicSinkCodeNode

/**
 * Constructs a EALogicControllerInterface backed by [DynamicPipelineController].
 * Per-flow-graph state lives in this function's closure — multiple
 * concurrent calls produce fully isolated controllers.
 *
 * @param fallbackLookup Resolves CodeNodeDefinitions for nodes other than
 *        the generated EALogicSourceCodeNode / EALogicSinkCodeNode wrappers (e.g., transformers,
 *        intermediate processors). The Runtime Preview path passes the
 *        NodeDefinitionRegistry-backed lookup here so any CodeNode added
 *        to the canvas resolves. Defaults to no-fallback for direct callers.
 */
fun createEALogicRuntime(
    flowGraph: FlowGraph,
    fallbackLookup: (String) -> CodeNodeDefinition? = { null }
): EALogicControllerInterface {
    val _out_mergedecision_output1 = MutableStateFlow<Any?>(null)
    val _in_conditionbranch_amount = MutableSharedFlow<Any>(replay = 1, extraBufferCapacity = 64)

    val sinkWrapper = EALogicSinkCodeNode.withReporters(
        { value -> _out_mergedecision_output1.value = value as Any? }
    )
    val sourceWrapper = EALogicSourceCodeNode.withSources(_in_conditionbranch_amount)

    val controller = DynamicPipelineController(
        flowGraphProvider = { flowGraph },
        lookup = { nodeName -> when (nodeName) {
            "EALogicSource" -> sourceWrapper
            "EALogicSink" -> sinkWrapper
            else -> fallbackLookup(nodeName)
        } },
        onReset = {
            _out_mergedecision_output1.value = null
        }
    )

    return object : EALogicControllerInterface, ModuleController by controller {
        override val out_mergedecision_output1: StateFlow<Any?> = _out_mergedecision_output1.asStateFlow()
        override fun emitIn_conditionbranch_amount(value: Any) {
            controller.coroutineScope?.launch { _in_conditionbranch_amount.emit(value) }
        }
    }
}
