/*
 * EALogicControllerInterface
 * Generated by CodeNodeIO UIFBPInterfaceGenerator (feature 087 / Design B additive)
 * License: Apache 2.0
 */

package io.codenode.expenseapproval.controller

import io.codenode.fbpdsl.runtime.ModuleController
import kotlinx.coroutines.flow.StateFlow

/**
 * Typed control surface for EALogic.
 *
 * Inherits start/stop/pause/resume/reset/getStatus/setAttenuationDelay/
 * setEmissionObserver/setValueObserver and executionState from [ModuleController].
 * Adds typed StateFlow members for each sink-input port the UI observes
 * AND additive emit<Port>(value) methods for each source-output port the UI raises
 * (Design B / FR-007 additive).
 */
interface EALogicControllerInterface : ModuleController {
    val amount: StateFlow<Any?>
    val status: StateFlow<ExpenseApprovalStatus?>
    val approver: StateFlow<Approver?>
    fun emitAmountChanged(value: Any)
    fun emitSubmitClicked()
}
