/*
 * AddressesRuntime — Universal-runtime factory for the Addresses module
 * Generated by CodeNodeIO ModuleRuntimeGenerator
 * License: Apache 2.0
 */

package io.codenode.addresses

import io.codenode.fbpdsl.model.FlowGraph
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.runtime.DynamicPipelineController
import io.codenode.fbpdsl.runtime.ModuleController
import io.codenode.addresses.controller.AddressesControllerInterface
import io.codenode.addresses.viewmodel.AddressesState
import io.codenode.addresses.nodes.AddressCUDCodeNode
import io.codenode.addresses.nodes.AddressRepositoryCodeNode
import io.codenode.addresses.nodes.AddressesDisplayCodeNode

/**
 * Module-local lookup for resolving node names to compiled CodeNodeDefinitions.
 * Used by [DynamicPipelineController] when running this module without the GraphEditor.
 */
object AddressesNodeRegistry {
    fun lookup(name: String): CodeNodeDefinition? = when (name) {
        "AddressCUD" -> AddressCUDCodeNode
        "AddressRepository" -> AddressRepositoryCodeNode
        "AddressesDisplay" -> AddressesDisplayCodeNode
        else -> null
    }
}

/**
 * Constructs an AddressesControllerInterface backed by [DynamicPipelineController].
 *
 * Production-app consumers call this directly. Note: the AddressesViewModel
 * constructor takes both this controller AND an `AddressDao` — the DAO is wired
 * at the consumer site (e.g., from `AddressesPersistence.dao`), not here.
 */
fun createAddressesRuntime(flowGraph: FlowGraph): AddressesControllerInterface {
    val controller = DynamicPipelineController(
        flowGraphProvider = { flowGraph },
        lookup = AddressesNodeRegistry::lookup,
        onReset = AddressesState::reset
    )
    return object : AddressesControllerInterface, ModuleController by controller {
        override val save = AddressesState.saveFlow
        override val update = AddressesState.updateFlow
        override val remove = AddressesState.removeFlow
        override val result = AddressesState.resultFlow
        override val error = AddressesState.errorFlow
    }
}
