/*
 * AddressesViewModel
 * Generated by CodeNodeIO RuntimeViewModelGenerator
 * License: Apache 2.0
 */

package io.codenode.addresses

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import io.codenode.fbpdsl.model.ExecutionState
import io.codenode.fbpdsl.model.FlowGraph
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import io.codenode.addresses.generated.AddressesControllerInterface
import io.codenode.persistence.AddressDao
import io.codenode.persistence.AddressEntity
import io.codenode.persistence.AddressRepository

// ===== MODULE PROPERTIES START =====
// Auto-generated from source output ports and sink input ports. Do not edit this section manually.
// Changes here will be overwritten on next code generation.

object AddressesState {

    internal val _save = MutableStateFlow<Any?>(null)
    val saveFlow: StateFlow<Any?> = _save.asStateFlow()

    internal val _update = MutableStateFlow<Any?>(null)
    val updateFlow: StateFlow<Any?> = _update.asStateFlow()

    internal val _remove = MutableStateFlow<Any?>(null)
    val removeFlow: StateFlow<Any?> = _remove.asStateFlow()

    internal val _result = MutableStateFlow<Any?>(null)
    val resultFlow: StateFlow<Any?> = _result.asStateFlow()

    internal val _error = MutableStateFlow<Any?>(null)
    val errorFlow: StateFlow<Any?> = _error.asStateFlow()

    internal val _addresses = MutableStateFlow<List<AddressEntity>>(emptyList())

    fun reset() {
        _save.value = null
        _update.value = null
        _remove.value = null
        _result.value = null
        _error.value = null
        _addresses.value = emptyList()
    }
}

// ===== MODULE PROPERTIES END =====

// ============================================================
// ViewModel
// Binding interface between composable UI and FlowGraph.
// User-editable section below — preserved across regenerations.
// ============================================================

/**
 * ViewModel for the Addresses composable.
 * Bridges FlowGraph domain logic with Compose UI.
 *
 * @param controller The AddressesControllerInterface that manages FlowGraph execution
 * @generated by CodeNodeIO RuntimeViewModelGenerator
 */
class AddressesViewModel(
    private val controller: AddressesControllerInterface,
    addressDao: AddressDao
) : ViewModel() {

    // Observable state from module properties
    val save: StateFlow<Any?> = AddressesState.saveFlow
    val update: StateFlow<Any?> = AddressesState.updateFlow
    val remove: StateFlow<Any?> = AddressesState.removeFlow
    val result: StateFlow<Any?> = AddressesState.resultFlow
    val error: StateFlow<Any?> = AddressesState.errorFlow

    // Reactive entity list from repository
    val addresses: StateFlow<List<AddressEntity>> = AddressesState._addresses

    // Execution state from controller
    val executionState: StateFlow<ExecutionState> = controller.executionState

    init {
        // Collect repository changes into the addresses StateFlow
        viewModelScope.launch {
            val repo = AddressRepository(addressDao)
            repo.observeAll().collect { list ->
                AddressesState._addresses.value = list
            }
        }
    }

    // CRUD methods — trigger operations via the FlowGraph reactive source
    fun addEntity(address: AddressEntity) {
        AddressesState._save.value = address
    }

    fun updateEntity(address: AddressEntity) {
        AddressesState._update.value = address
    }

    fun removeEntity(address: AddressEntity) {
        AddressesState._remove.value = address
    }

    // Control methods
    fun start(): FlowGraph = controller.start()

    fun stop(): FlowGraph = controller.stop()

    fun reset(): FlowGraph = controller.reset()

    fun pause(): FlowGraph = controller.pause()

    fun resume(): FlowGraph = controller.resume()
}

