/*
 * AddressCUD Source Node
 * Generated by CodeNodeIO EntityCUDGenerator
 * License: Apache 2.0
 */

package io.codenode.addresses

import io.codenode.fbpdsl.model.CodeNodeFactory
import io.codenode.fbpdsl.runtime.ProcessResult3
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.flow.drop
import kotlinx.coroutines.launch

/**
 * Creates the AddressCUD source node.
 *
 * This source node collects from the save, update, and remove StateFlows
 * in AddressesState and emits them as a ProcessResult3 to downstream processors.
 */
internal fun createAddressCUD() = CodeNodeFactory.createSourceOut3<Any, Any, Any>(
    name = "AddressCUD",
    generate = { emit ->
        coroutineScope {
            launch {
                AddressesState._save.drop(1).collect { save ->
                    if (save != null) {
                        emit(ProcessResult3(save, null, null))
                        AddressesState._save.value = null
                    }
                }
            }
            launch {
                AddressesState._update.drop(1).collect { update ->
                    if (update != null) {
                        emit(ProcessResult3(null, update, null))
                        AddressesState._update.value = null
                    }
                }
            }
            launch {
                AddressesState._remove.drop(1).collect { remove ->
                    if (remove != null) {
                        emit(ProcessResult3(null, null, remove))
                        AddressesState._remove.value = null
                    }
                }
            }
        }
    }
)
