/*
 * AddressesDisplay Sink Node
 * Generated by CodeNodeIO EntityDisplayGenerator
 * License: Apache 2.0
 */

package io.codenode.addresses

import io.codenode.fbpdsl.model.CodeNodeFactory

/**
 * Creates the AddressesDisplay sink node.
 *
 * This sink node receives result and error values from the AddressRepository
 * processor and updates the corresponding StateFlows in AddressesState.
 */
internal fun createAddressesDisplay() = CodeNodeFactory.createSinkIn2<Any, Any>(
    name = "AddressesDisplay",
    consume = { result, error ->
        AddressesState._result.value = result
        AddressesState._error.value = error
    }
)
