/*
 * EdgeArtFilterControllerInterface
 * Generated by CodeNodeIO RuntimeControllerInterfaceGenerator
 * License: Apache 2.0
 */

package io.codenode.edgeartfilter.controller

import io.codenode.edgeartfilter.iptypes.ImageData
import io.codenode.fbpdsl.model.ExecutionState
import io.codenode.fbpdsl.model.FlowGraph
import kotlinx.coroutines.flow.StateFlow

/**
 * Interface defining the contract for EdgeArtFilter controllers.
 *
 * Enables dependency injection and testing by allowing
 * both the real EdgeArtFilterController and test fakes to be used.
 *
 * @generated by CodeNodeIO RuntimeControllerInterfaceGenerator
 */
interface EdgeArtFilterControllerInterface {

    val executionState: StateFlow<ExecutionState>

    fun start(): FlowGraph

    fun stop(): FlowGraph

    fun reset(): FlowGraph

    fun pause(): FlowGraph

    fun resume(): FlowGraph
}
