/*
 * EdgeArtFilterRuntime — Universal-runtime factory for the EdgeArtFilter module
 * Generated by CodeNodeIO ModuleRuntimeGenerator
 * License: Apache 2.0
 */

package io.codenode.edgeartfilter.controller

import io.codenode.fbpdsl.model.FlowGraph
import io.codenode.fbpdsl.runtime.CodeNodeDefinition
import io.codenode.fbpdsl.runtime.DynamicPipelineController
import io.codenode.fbpdsl.runtime.ModuleController
import io.codenode.edgeartfilter.EdgeArtFilterState
import io.codenode.edgeartfilter.nodes.ColorOverlayCodeNode
import io.codenode.edgeartfilter.nodes.EdgeDetectorCodeNode
import io.codenode.edgeartfilter.nodes.GrayscaleTransformerCodeNode
import io.codenode.edgeartfilter.nodes.ImagePickerCodeNode
import io.codenode.edgeartfilter.nodes.ImageViewerCodeNode
import io.codenode.edgeartfilter.nodes.SepiaTransformerCodeNode

/**
 * Module-local lookup for resolving node names to compiled CodeNodeDefinitions.
 * Used by [DynamicPipelineController] when running this module without the GraphEditor.
 */
object EdgeArtFilterNodeRegistry {
    fun lookup(name: String): CodeNodeDefinition? = when (name) {
        "ColorOverlay" -> ColorOverlayCodeNode
        "EdgeDetector" -> EdgeDetectorCodeNode
        "GrayscaleTransformer" -> GrayscaleTransformerCodeNode
        "ImagePicker" -> ImagePickerCodeNode
        "ImageViewer" -> ImageViewerCodeNode
        "SepiaTransformer" -> SepiaTransformerCodeNode
        else -> null
    }
}

/**
 * Constructs an EdgeArtFilterControllerInterface backed by [DynamicPipelineController].
 */
fun createEdgeArtFilterRuntime(flowGraph: FlowGraph): EdgeArtFilterControllerInterface {
    val controller = DynamicPipelineController(
        flowGraphProvider = { flowGraph },
        lookup = EdgeArtFilterNodeRegistry::lookup,
        onReset = EdgeArtFilterState::reset
    )
    return object : EdgeArtFilterControllerInterface, ModuleController by controller {}
}
