/*
 * EdgeArtFilterControllerInterface
 * Generated by CodeNodeIO RuntimeControllerInterfaceGenerator
 * License: Apache 2.0
 */

package io.codenode.edgeartfilter.controller

import io.codenode.fbpdsl.runtime.ModuleController

/**
 * Interface defining the contract for EdgeArtFilter controllers.
 *
 * Extends [ModuleController] (feature 085 — universal-runtime collapse) so
 * consumers reach setAttenuationDelay/observers/getStatus through this typed
 * surface without casting to a concrete controller class.
 *
 * @generated by CodeNodeIO RuntimeControllerInterfaceGenerator
 */
interface EdgeArtFilterControllerInterface : ModuleController
