/*
 * EdgeArtFilter Controller
 * Generated by CodeNodeIO RuntimeControllerGenerator
 * License: Apache 2.0
 */

package io.codenode.edgeartfilter.controller
import io.codenode.edgeartfilter.flow.EdgeArtFilterFlow

import io.codenode.edgeartfilter.EdgeArtFilterState

import io.codenode.fbpdsl.model.RootControlNode
import io.codenode.fbpdsl.model.FlowGraph
import io.codenode.fbpdsl.model.FlowExecutionStatus
import io.codenode.fbpdsl.model.ExecutionState
import io.codenode.fbpdsl.model.ControlConfig
import io.codenode.fbpdsl.runtime.ModuleController
import io.codenode.fbpdsl.runtime.RuntimeRegistry
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.LifecycleEventObserver
import androidx.lifecycle.LifecycleOwner
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

/**
 * Controller for EdgeArtFilter flow execution.
 *
 * Provides unified control operations for starting, pausing,
 * stopping, and monitoring the flow execution.
 *
 * @param flowGraph The FlowGraph instance to control
 * @generated by CodeNodeIO RuntimeControllerGenerator
 */
class EdgeArtFilterController(
    private var flowGraph: FlowGraph
) : ModuleController {

    private val registry = RuntimeRegistry()

    private var controller: RootControlNode = RootControlNode.createFor(
        flowGraph = flowGraph,
        name = "EdgeArtFilterController",
        registry = registry
    )

    private val flow = EdgeArtFilterFlow()

    private var flowScope: CoroutineScope? = null

    private var wasRunningBeforePause: Boolean = false

    private var emissionObserver: ((String, Int) -> Unit)? = null
    private var valueObserver: ((String, Int, Any?) -> Unit)? = null

    private val _executionState = MutableStateFlow(ExecutionState.IDLE)
    override val executionState: StateFlow<ExecutionState> = _executionState.asStateFlow()

    override var nodeDefinitionLookup: ((String) -> io.codenode.fbpdsl.runtime.CodeNodeDefinition?)?
        = null

    override fun start(): FlowGraph {
        flowGraph = controller.startAll()
        controller = RootControlNode.createFor(flowGraph, "EdgeArtFilterController", registry)
        _executionState.value = ExecutionState.RUNNING

        flowScope?.cancel()
        val scope = CoroutineScope(SupervisorJob() + Dispatchers.Default)
        flowScope = scope

        flow.imagePicker.registry = registry
        flow.grayscaleTransformer.registry = registry
        flow.edgeDetector.registry = registry
        flow.colorOverlay.registry = registry
        flow.imageViewer.registry = registry

        flow.imagePicker.executionState = ExecutionState.RUNNING

        // Apply emission and value observers to all runtimes
        applyEmissionObserver()
        applyValueObserver()

        scope.launch {
            flow.start(scope)
        }

        return flowGraph
    }

    override fun pause(): FlowGraph {
        flowGraph = controller.pauseAll()
        controller = RootControlNode.createFor(flowGraph, "EdgeArtFilterController", registry)
        _executionState.value = ExecutionState.PAUSED
        return flowGraph
    }

    override fun resume(): FlowGraph {
        flowGraph = controller.resumeAll()
        controller = RootControlNode.createFor(flowGraph, "EdgeArtFilterController", registry)
        _executionState.value = ExecutionState.RUNNING
        return flowGraph
    }

    override fun stop(): FlowGraph {
        flowGraph = controller.stopAll()
        controller = RootControlNode.createFor(flowGraph, "EdgeArtFilterController", registry)
        _executionState.value = ExecutionState.IDLE

        flow.stop()
        flowScope?.cancel()
        flowScope = null

        return flowGraph
    }

    override fun reset(): FlowGraph {
        wasRunningBeforePause = false
        stop()
        flow.reset()
        return flowGraph
    }

    fun getStatus(): FlowExecutionStatus {
        return controller.getStatus()
    }

    fun setNodeState(nodeId: String, state: ExecutionState): FlowGraph {
        flowGraph = controller.setNodeState(nodeId, state)
        controller = RootControlNode.createFor(flowGraph, "EdgeArtFilterController")
        return flowGraph
    }

    fun setNodeConfig(nodeId: String, config: ControlConfig): FlowGraph {
        flowGraph = controller.setNodeConfig(nodeId, config)
        controller = RootControlNode.createFor(flowGraph, "EdgeArtFilterController")
        return flowGraph
    }

    fun bindToLifecycle(lifecycle: Lifecycle) {
        lifecycle.addObserver(object : LifecycleEventObserver {
            override fun onStateChanged(source: LifecycleOwner, event: Lifecycle.Event) {
                when (event) {
                    Lifecycle.Event.ON_START -> {
                        if (wasRunningBeforePause) {
                            start()
                            wasRunningBeforePause = false
                        }
                    }
                    Lifecycle.Event.ON_STOP -> {
                        val status = getStatus()
                        wasRunningBeforePause = status.overallState == ExecutionState.RUNNING
                        if (wasRunningBeforePause) {
                            pause()
                        }
                    }
                    Lifecycle.Event.ON_DESTROY -> {
                        stop()
                    }
                    else -> { /* no-op */ }
                }
            }
        })
    }

    override fun setAttenuationDelay(ms: Long?) {
        flow.imagePicker.attenuationDelayMs = ms
        flow.grayscaleTransformer.attenuationDelayMs = ms
        flow.edgeDetector.attenuationDelayMs = ms
        flow.colorOverlay.attenuationDelayMs = ms
        flow.imageViewer.attenuationDelayMs = ms
    }

    override fun setEmissionObserver(observer: ((String, Int) -> Unit)?) {
        emissionObserver = observer
        applyEmissionObserver()
    }

    private fun applyEmissionObserver() {
        val obs = emissionObserver
        flow.imagePicker.onEmit = obs
        flow.grayscaleTransformer.onEmit = obs
        flow.edgeDetector.onEmit = obs
        flow.colorOverlay.onEmit = obs
        flow.imageViewer.onEmit = obs
    }

    override fun setValueObserver(observer: ((String, Int, Any?) -> Unit)?) {
        valueObserver = observer
        applyValueObserver()
    }

    private fun applyValueObserver() {
        val obs = valueObserver
        flow.imagePicker.onEmitValue = obs
        flow.grayscaleTransformer.onEmitValue = obs
        flow.edgeDetector.onEmitValue = obs
        flow.colorOverlay.onEmitValue = obs
        flow.imageViewer.onEmitValue = obs
    }

    val currentFlowGraph: FlowGraph
        get() = flowGraph
}
