/*
 * GreeterViewModel
 * Generated by CodeNodeIO UIFBPViewModelGenerator (feature 087 / Design B)
 * License: Apache 2.0
 */

package io.codenode.greeter.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import io.codenode.fbpdsl.model.ExecutionState
import io.codenode.fbpdsl.model.FlowGraph
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import io.codenode.greeter.controller.GreeterControllerInterface

class GreeterViewModel(
    private val controller: GreeterControllerInterface
) : ViewModel() {

    private val _state = MutableStateFlow(GreeterState())
    val state: StateFlow<GreeterState> = _state.asStateFlow()

    val executionState: StateFlow<ExecutionState> = controller.executionState

    init {
        viewModelScope.launch {
            controller.greeting.collect { value ->
                _state.update { it.copy(greeting = value) }
            }
        }
        viewModelScope.launch {
            controller.nameLength.collect { value ->
                _state.update { it.copy(nameLength = value) }
            }
        }
    }

    fun onEvent(event: GreeterEvent) {
        when (event) {
            is GreeterEvent.UpdateName -> controller.emitName(event.value)
        }
    }

    fun start(): FlowGraph = controller.start()
    fun stop(): FlowGraph = controller.stop()
    fun pause(): FlowGraph = controller.pause()
    fun resume(): FlowGraph = controller.resume()
    fun reset(): FlowGraph = controller.reset()
}
