/*
 * GreeterState
 * Generated by CodeNodeIO UIFBPStateGenerator (feature 087 / Design B)
 * License: Apache 2.0
 */

package io.codenode.greeter.viewmodel

data class GreeterState(
    val greeting: String = "",
    val nameLength: Int = 0
)
