/*
 * GreeterEvent
 * Generated by CodeNodeIO UIFBPEventGenerator (feature 087 / FR-002)
 * License: Apache 2.0
 */

package io.codenode.greeter.viewmodel

sealed interface GreeterEvent {
    data class UpdateName(val value: String) : GreeterEvent
}
